//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Data models for describing a software.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: software.proto

package software_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Type of the Version message, identifying an ordinary software version or a
// sentinel MINIMUM/MAXIMUM version. See comments below for what is a sentinel
// version.
type Version_VersionType int32

const (
	Version_VERSION_TYPE_UNSPECIFIED Version_VersionType = 0
	// A normal software version.
	Version_NORMAL Version_VersionType = 1
	// A sentinel version representing negative infinity, i.e. MINIMUM version
	// is less than any NORMAL and MAXIMUM versions.
	Version_MINIMUM Version_VersionType = 2
	// A sentinel version representing positive infinity, i.e. MAXIMUM version
	// is greater than any NORMAL and MINIMUM versions.
	Version_MAXIMUM Version_VersionType = 3
)

// Enum value maps for Version_VersionType.
var (
	Version_VersionType_name = map[int32]string{
		0: "VERSION_TYPE_UNSPECIFIED",
		1: "NORMAL",
		2: "MINIMUM",
		3: "MAXIMUM",
	}
	Version_VersionType_value = map[string]int32{
		"VERSION_TYPE_UNSPECIFIED": 0,
		"NORMAL":                   1,
		"MINIMUM":                  2,
		"MAXIMUM":                  3,
	}
)

func (x Version_VersionType) Enum() *Version_VersionType {
	p := new(Version_VersionType)
	*p = x
	return p
}

func (x Version_VersionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Version_VersionType) Descriptor() protoreflect.EnumDescriptor {
	return file_software_proto_enumTypes[0].Descriptor()
}

func (Version_VersionType) Type() protoreflect.EnumType {
	return &file_software_proto_enumTypes[0]
}

func (x Version_VersionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Whether the range endpoint is inclusive or exclusive.
type VersionRange_Inclusiveness int32

const (
	VersionRange_INCLUSIVENESS_UNSPECIFIED VersionRange_Inclusiveness = 0
	VersionRange_INCLUSIVE                 VersionRange_Inclusiveness = 1
	VersionRange_EXCLUSIVE                 VersionRange_Inclusiveness = 2
)

// Enum value maps for VersionRange_Inclusiveness.
var (
	VersionRange_Inclusiveness_name = map[int32]string{
		0: "INCLUSIVENESS_UNSPECIFIED",
		1: "INCLUSIVE",
		2: "EXCLUSIVE",
	}
	VersionRange_Inclusiveness_value = map[string]int32{
		"INCLUSIVENESS_UNSPECIFIED": 0,
		"INCLUSIVE":                 1,
		"EXCLUSIVE":                 2,
	}
)

func (x VersionRange_Inclusiveness) Enum() *VersionRange_Inclusiveness {
	p := new(VersionRange_Inclusiveness)
	*p = x
	return p
}

func (x VersionRange_Inclusiveness) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VersionRange_Inclusiveness) Descriptor() protoreflect.EnumDescriptor {
	return file_software_proto_enumTypes[1].Descriptor()
}

func (VersionRange_Inclusiveness) Type() protoreflect.EnumType {
	return &file_software_proto_enumTypes[1]
}

func (x VersionRange_Inclusiveness) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The exact version of a software.
type Version struct {
	state                        protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type              Version_VersionType    `protobuf:"varint,1,opt,name=type,proto3,enum=tsunami.proto.Version_VersionType"`
	xxx_hidden_FullVersionString string                 `protobuf:"bytes,2,opt,name=full_version_string,json=fullVersionString,proto3"`
	unknownFields                protoimpl.UnknownFields
	sizeCache                    protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_software_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_software_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Version) GetType() Version_VersionType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return Version_VERSION_TYPE_UNSPECIFIED
}

func (x *Version) GetFullVersionString() string {
	if x != nil {
		return x.xxx_hidden_FullVersionString
	}
	return ""
}

func (x *Version) SetType(v Version_VersionType) {
	x.xxx_hidden_Type = v
}

func (x *Version) SetFullVersionString(v string) {
	x.xxx_hidden_FullVersionString = v
}

type Version_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Distinguishes between sentinel MIN/MAX versions and normal versions.
	Type Version_VersionType
	// Human readable version number, e.g. 1.0.3. This is set only when type is
	// NORMAL. Tsunami uses raw string to represent a version number instead of
	// any structured messages in order to handle different kinds of version
	// schemes. Tsunami will tokenize this version string and store tokens
	// internally. When performing version comparisons, Tsunami follows the
	// precedence defined by Semantic Versioning (semver.org). More details can be
	// found in Tsunami's internal Version class.
	FullVersionString string
}

func (b0 Version_builder) Build() *Version {
	m0 := &Version{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_FullVersionString = b.FullVersionString
	return m0
}

// An inclusive range of versions for a software.
type VersionRange struct {
	state                              protoimpl.MessageState     `protogen:"opaque.v1"`
	xxx_hidden_MinVersion              *Version                   `protobuf:"bytes,1,opt,name=min_version,json=minVersion,proto3"`
	xxx_hidden_MinVersionInclusiveness VersionRange_Inclusiveness `protobuf:"varint,2,opt,name=min_version_inclusiveness,json=minVersionInclusiveness,proto3,enum=tsunami.proto.VersionRange_Inclusiveness"`
	xxx_hidden_MaxVersion              *Version                   `protobuf:"bytes,3,opt,name=max_version,json=maxVersion,proto3"`
	xxx_hidden_MaxVersionInclusiveness VersionRange_Inclusiveness `protobuf:"varint,4,opt,name=max_version_inclusiveness,json=maxVersionInclusiveness,proto3,enum=tsunami.proto.VersionRange_Inclusiveness"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *VersionRange) Reset() {
	*x = VersionRange{}
	mi := &file_software_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionRange) ProtoMessage() {}

func (x *VersionRange) ProtoReflect() protoreflect.Message {
	mi := &file_software_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VersionRange) GetMinVersion() *Version {
	if x != nil {
		return x.xxx_hidden_MinVersion
	}
	return nil
}

func (x *VersionRange) GetMinVersionInclusiveness() VersionRange_Inclusiveness {
	if x != nil {
		return x.xxx_hidden_MinVersionInclusiveness
	}
	return VersionRange_INCLUSIVENESS_UNSPECIFIED
}

func (x *VersionRange) GetMaxVersion() *Version {
	if x != nil {
		return x.xxx_hidden_MaxVersion
	}
	return nil
}

func (x *VersionRange) GetMaxVersionInclusiveness() VersionRange_Inclusiveness {
	if x != nil {
		return x.xxx_hidden_MaxVersionInclusiveness
	}
	return VersionRange_INCLUSIVENESS_UNSPECIFIED
}

func (x *VersionRange) SetMinVersion(v *Version) {
	x.xxx_hidden_MinVersion = v
}

func (x *VersionRange) SetMinVersionInclusiveness(v VersionRange_Inclusiveness) {
	x.xxx_hidden_MinVersionInclusiveness = v
}

func (x *VersionRange) SetMaxVersion(v *Version) {
	x.xxx_hidden_MaxVersion = v
}

func (x *VersionRange) SetMaxVersionInclusiveness(v VersionRange_Inclusiveness) {
	x.xxx_hidden_MaxVersionInclusiveness = v
}

func (x *VersionRange) HasMinVersion() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MinVersion != nil
}

func (x *VersionRange) HasMaxVersion() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_MaxVersion != nil
}

func (x *VersionRange) ClearMinVersion() {
	x.xxx_hidden_MinVersion = nil
}

func (x *VersionRange) ClearMaxVersion() {
	x.xxx_hidden_MaxVersion = nil
}

type VersionRange_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Minimum version that belongs in the range.
	MinVersion *Version
	// Inclusiveness of the min_version. When min_version points to negative
	// infinity, this value will always be EXCLUSIVE to matching the
	// representation of (-inf, 1.0]. Note that negative infinity version should
	// ***NOT*** be compared with a version range as it is just a bogus sentinel
	// version without any meaning.
	MinVersionInclusiveness VersionRange_Inclusiveness
	// Maximum version that belongs in the range.
	MaxVersion *Version
	// Inclusiveness of the max_version. When max_version points to positive
	// infinity, this value will always be EXCLUSIVE to matching the
	// representation of [1.0, inf). Note that positive infinity version should
	// ***NOT*** be compared with a version range as it is just a bogus sentinel
	// version without any meaning.
	MaxVersionInclusiveness VersionRange_Inclusiveness
}

func (b0 VersionRange_builder) Build() *VersionRange {
	m0 := &VersionRange{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_MinVersion = b.MinVersion
	x.xxx_hidden_MinVersionInclusiveness = b.MinVersionInclusiveness
	x.xxx_hidden_MaxVersion = b.MaxVersion
	x.xxx_hidden_MaxVersionInclusiveness = b.MaxVersionInclusiveness
	return m0
}

// A set of Versions and VersionRanges that completely describes a set of
// software releases, e.g. {3.9.1, 3.9.3, [4.7.1, 4.7.8], 4.8}
type VersionSet struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Versions      *[]*Version            `protobuf:"bytes,1,rep,name=versions,proto3"`
	xxx_hidden_VersionRanges *[]*VersionRange       `protobuf:"bytes,2,rep,name=version_ranges,json=versionRanges,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *VersionSet) Reset() {
	*x = VersionSet{}
	mi := &file_software_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionSet) ProtoMessage() {}

func (x *VersionSet) ProtoReflect() protoreflect.Message {
	mi := &file_software_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *VersionSet) GetVersions() []*Version {
	if x != nil {
		if x.xxx_hidden_Versions != nil {
			return *x.xxx_hidden_Versions
		}
	}
	return nil
}

func (x *VersionSet) GetVersionRanges() []*VersionRange {
	if x != nil {
		if x.xxx_hidden_VersionRanges != nil {
			return *x.xxx_hidden_VersionRanges
		}
	}
	return nil
}

func (x *VersionSet) SetVersions(v []*Version) {
	x.xxx_hidden_Versions = &v
}

func (x *VersionSet) SetVersionRanges(v []*VersionRange) {
	x.xxx_hidden_VersionRanges = &v
}

type VersionSet_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Versions      []*Version
	VersionRanges []*VersionRange
}

func (b0 VersionSet_builder) Build() *VersionSet {
	m0 := &VersionSet{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Versions = &b.Versions
	x.xxx_hidden_VersionRanges = &b.VersionRanges
	return m0
}

// A structured description about a software.
type Software struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Software) Reset() {
	*x = Software{}
	mi := &file_software_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Software) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Software) ProtoMessage() {}

func (x *Software) ProtoReflect() protoreflect.Message {
	mi := &file_software_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Software) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Software) SetName(v string) {
	x.xxx_hidden_Name = v
}

type Software_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name of this software.
	Name string
}

func (b0 Software_builder) Build() *Software {
	m0 := &Software{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

var File_software_proto protoreflect.FileDescriptor

const file_software_proto_rawDesc = "" +
	"\n" +
	"\x0esoftware.proto\x12\rtsunami.proto\"\xc4\x01\n" +
	"\aVersion\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".tsunami.proto.Version.VersionTypeR\x04type\x12.\n" +
	"\x13full_version_string\x18\x02 \x01(\tR\x11fullVersionString\"Q\n" +
	"\vVersionType\x12\x1c\n" +
	"\x18VERSION_TYPE_UNSPECIFIED\x10\x00\x12\n" +
	"\n" +
	"\x06NORMAL\x10\x01\x12\v\n" +
	"\aMINIMUM\x10\x02\x12\v\n" +
	"\aMAXIMUM\x10\x03\"\x9c\x03\n" +
	"\fVersionRange\x127\n" +
	"\vmin_version\x18\x01 \x01(\v2\x16.tsunami.proto.VersionR\n" +
	"minVersion\x12e\n" +
	"\x19min_version_inclusiveness\x18\x02 \x01(\x0e2).tsunami.proto.VersionRange.InclusivenessR\x17minVersionInclusiveness\x127\n" +
	"\vmax_version\x18\x03 \x01(\v2\x16.tsunami.proto.VersionR\n" +
	"maxVersion\x12e\n" +
	"\x19max_version_inclusiveness\x18\x04 \x01(\x0e2).tsunami.proto.VersionRange.InclusivenessR\x17maxVersionInclusiveness\"L\n" +
	"\rInclusiveness\x12\x1d\n" +
	"\x19INCLUSIVENESS_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tINCLUSIVE\x10\x01\x12\r\n" +
	"\tEXCLUSIVE\x10\x02\"\x84\x01\n" +
	"\n" +
	"VersionSet\x122\n" +
	"\bversions\x18\x01 \x03(\v2\x16.tsunami.proto.VersionR\bversions\x12B\n" +
	"\x0eversion_ranges\x18\x02 \x03(\v2\x1b.tsunami.proto.VersionRangeR\rversionRanges\"\x1e\n" +
	"\bSoftware\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04nameBs\n" +
	"\x18com.google.tsunami.protoB\x0eSoftwareProtosP\x01ZEgithub.com/google/tsunami-security-scanner/proto/go/software_go_protob\x06proto3"

var file_software_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_software_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_software_proto_goTypes = []any{
	(Version_VersionType)(0),        // 0: tsunami.proto.Version.VersionType
	(VersionRange_Inclusiveness)(0), // 1: tsunami.proto.VersionRange.Inclusiveness
	(*Version)(nil),                 // 2: tsunami.proto.Version
	(*VersionRange)(nil),            // 3: tsunami.proto.VersionRange
	(*VersionSet)(nil),              // 4: tsunami.proto.VersionSet
	(*Software)(nil),                // 5: tsunami.proto.Software
}
var file_software_proto_depIdxs = []int32{
	0, // 0: tsunami.proto.Version.type:type_name -> tsunami.proto.Version.VersionType
	2, // 1: tsunami.proto.VersionRange.min_version:type_name -> tsunami.proto.Version
	1, // 2: tsunami.proto.VersionRange.min_version_inclusiveness:type_name -> tsunami.proto.VersionRange.Inclusiveness
	2, // 3: tsunami.proto.VersionRange.max_version:type_name -> tsunami.proto.Version
	1, // 4: tsunami.proto.VersionRange.max_version_inclusiveness:type_name -> tsunami.proto.VersionRange.Inclusiveness
	2, // 5: tsunami.proto.VersionSet.versions:type_name -> tsunami.proto.Version
	3, // 6: tsunami.proto.VersionSet.version_ranges:type_name -> tsunami.proto.VersionRange
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_software_proto_init() }
func file_software_proto_init() {
	if File_software_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_software_proto_rawDesc), len(file_software_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_software_proto_goTypes,
		DependencyIndexes: file_software_proto_depIdxs,
		EnumInfos:         file_software_proto_enumTypes,
		MessageInfos:      file_software_proto_msgTypes,
	}.Build()
	File_software_proto = out.File
	file_software_proto_goTypes = nil
	file_software_proto_depIdxs = nil
}
