//
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Data models for the web crawler.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: web_crawl.proto

package web_crawl_go_proto

import (
	network_go_proto "github.com/google/tsunami-security-scanner/proto/go/network_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Next ID: 7
type CrawlConfig struct {
	state                              protoimpl.MessageState            `protogen:"opaque.v1"`
	xxx_hidden_SeedingUrls             []string                          `protobuf:"bytes,1,rep,name=seeding_urls,json=seedingUrls,proto3"`
	xxx_hidden_MaxDepth                int32                             `protobuf:"varint,2,opt,name=max_depth,json=maxDepth,proto3"`
	xxx_hidden_Scopes                  *[]*CrawlConfig_Scope             `protobuf:"bytes,3,rep,name=scopes,proto3"`
	xxx_hidden_ShouldEnforceScopeCheck bool                              `protobuf:"varint,5,opt,name=should_enforce_scope_check,json=shouldEnforceScopeCheck,proto3"`
	xxx_hidden_NetworkEndpoint         *network_go_proto.NetworkEndpoint `protobuf:"bytes,6,opt,name=network_endpoint,json=networkEndpoint,proto3"`
	unknownFields                      protoimpl.UnknownFields
	sizeCache                          protoimpl.SizeCache
}

func (x *CrawlConfig) Reset() {
	*x = CrawlConfig{}
	mi := &file_web_crawl_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlConfig) ProtoMessage() {}

func (x *CrawlConfig) ProtoReflect() protoreflect.Message {
	mi := &file_web_crawl_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CrawlConfig) GetSeedingUrls() []string {
	if x != nil {
		return x.xxx_hidden_SeedingUrls
	}
	return nil
}

func (x *CrawlConfig) GetMaxDepth() int32 {
	if x != nil {
		return x.xxx_hidden_MaxDepth
	}
	return 0
}

func (x *CrawlConfig) GetScopes() []*CrawlConfig_Scope {
	if x != nil {
		if x.xxx_hidden_Scopes != nil {
			return *x.xxx_hidden_Scopes
		}
	}
	return nil
}

func (x *CrawlConfig) GetShouldEnforceScopeCheck() bool {
	if x != nil {
		return x.xxx_hidden_ShouldEnforceScopeCheck
	}
	return false
}

func (x *CrawlConfig) GetNetworkEndpoint() *network_go_proto.NetworkEndpoint {
	if x != nil {
		return x.xxx_hidden_NetworkEndpoint
	}
	return nil
}

func (x *CrawlConfig) SetSeedingUrls(v []string) {
	x.xxx_hidden_SeedingUrls = v
}

func (x *CrawlConfig) SetMaxDepth(v int32) {
	x.xxx_hidden_MaxDepth = v
}

func (x *CrawlConfig) SetScopes(v []*CrawlConfig_Scope) {
	x.xxx_hidden_Scopes = &v
}

func (x *CrawlConfig) SetShouldEnforceScopeCheck(v bool) {
	x.xxx_hidden_ShouldEnforceScopeCheck = v
}

func (x *CrawlConfig) SetNetworkEndpoint(v *network_go_proto.NetworkEndpoint) {
	x.xxx_hidden_NetworkEndpoint = v
}

func (x *CrawlConfig) HasNetworkEndpoint() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NetworkEndpoint != nil
}

func (x *CrawlConfig) ClearNetworkEndpoint() {
	x.xxx_hidden_NetworkEndpoint = nil
}

type CrawlConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Starting points of a web crawl.
	// Required.
	SeedingUrls []string
	// The maximum depth of a web crawl.
	// Required.
	MaxDepth int32
	// Allowed crawling scopes.
	// Optional. When empty, scopes are autogenerated from seeding_urls.
	Scopes []*CrawlConfig_Scope
	// Whether crawling scope check should be enforced.
	// Optional.
	ShouldEnforceScopeCheck bool
	// The network endpoint to be crawled.
	// Required.
	NetworkEndpoint *network_go_proto.NetworkEndpoint
}

func (b0 CrawlConfig_builder) Build() *CrawlConfig {
	m0 := &CrawlConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_SeedingUrls = b.SeedingUrls
	x.xxx_hidden_MaxDepth = b.MaxDepth
	x.xxx_hidden_Scopes = &b.Scopes
	x.xxx_hidden_ShouldEnforceScopeCheck = b.ShouldEnforceScopeCheck
	x.xxx_hidden_NetworkEndpoint = b.NetworkEndpoint
	return m0
}

type CrawlTarget struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Url             string                 `protobuf:"bytes,1,opt,name=url,proto3"`
	xxx_hidden_HttpMethod      string                 `protobuf:"bytes,2,opt,name=http_method,json=httpMethod,proto3"`
	xxx_hidden_HttpRequestBody []byte                 `protobuf:"bytes,3,opt,name=http_request_body,json=httpRequestBody,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CrawlTarget) Reset() {
	*x = CrawlTarget{}
	mi := &file_web_crawl_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlTarget) ProtoMessage() {}

func (x *CrawlTarget) ProtoReflect() protoreflect.Message {
	mi := &file_web_crawl_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CrawlTarget) GetUrl() string {
	if x != nil {
		return x.xxx_hidden_Url
	}
	return ""
}

func (x *CrawlTarget) GetHttpMethod() string {
	if x != nil {
		return x.xxx_hidden_HttpMethod
	}
	return ""
}

func (x *CrawlTarget) GetHttpRequestBody() []byte {
	if x != nil {
		return x.xxx_hidden_HttpRequestBody
	}
	return nil
}

func (x *CrawlTarget) SetUrl(v string) {
	x.xxx_hidden_Url = v
}

func (x *CrawlTarget) SetHttpMethod(v string) {
	x.xxx_hidden_HttpMethod = v
}

func (x *CrawlTarget) SetHttpRequestBody(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_HttpRequestBody = v
}

type CrawlTarget_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The URL pointing to the document.
	Url string
	// HTTP method to reach the url. Value must be in all upper case, like "GET".
	HttpMethod string
	// An optional HTTP request body sent to the crawl URL.
	HttpRequestBody []byte
}

func (b0 CrawlTarget_builder) Build() *CrawlTarget {
	m0 := &CrawlTarget{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Url = b.Url
	x.xxx_hidden_HttpMethod = b.HttpMethod
	x.xxx_hidden_HttpRequestBody = b.HttpRequestBody
	return m0
}

// Represents an HTTP header.
type HttpHeader struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Key   string                 `protobuf:"bytes,1,opt,name=key,proto3"`
	xxx_hidden_Value string                 `protobuf:"bytes,2,opt,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HttpHeader) Reset() {
	*x = HttpHeader{}
	mi := &file_web_crawl_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpHeader) ProtoMessage() {}

func (x *HttpHeader) ProtoReflect() protoreflect.Message {
	mi := &file_web_crawl_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *HttpHeader) GetKey() string {
	if x != nil {
		return x.xxx_hidden_Key
	}
	return ""
}

func (x *HttpHeader) GetValue() string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return ""
}

func (x *HttpHeader) SetKey(v string) {
	x.xxx_hidden_Key = v
}

func (x *HttpHeader) SetValue(v string) {
	x.xxx_hidden_Value = v
}

type HttpHeader_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Key   string
	Value string
}

func (b0 HttpHeader_builder) Build() *HttpHeader {
	m0 := &HttpHeader{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Key = b.Key
	x.xxx_hidden_Value = b.Value
	return m0
}

type CrawlResult struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CrawlTarget     *CrawlTarget           `protobuf:"bytes,1,opt,name=crawl_target,json=crawlTarget,proto3"`
	xxx_hidden_CrawlDepth      int32                  `protobuf:"varint,2,opt,name=crawl_depth,json=crawlDepth,proto3"`
	xxx_hidden_ResponseCode    int32                  `protobuf:"varint,3,opt,name=response_code,json=responseCode,proto3"`
	xxx_hidden_ContentType     string                 `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3"`
	xxx_hidden_Content         []byte                 `protobuf:"bytes,5,opt,name=content,proto3"`
	xxx_hidden_ResponseHeaders *[]*HttpHeader         `protobuf:"bytes,6,rep,name=response_headers,json=responseHeaders,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *CrawlResult) Reset() {
	*x = CrawlResult{}
	mi := &file_web_crawl_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlResult) ProtoMessage() {}

func (x *CrawlResult) ProtoReflect() protoreflect.Message {
	mi := &file_web_crawl_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CrawlResult) GetCrawlTarget() *CrawlTarget {
	if x != nil {
		return x.xxx_hidden_CrawlTarget
	}
	return nil
}

func (x *CrawlResult) GetCrawlDepth() int32 {
	if x != nil {
		return x.xxx_hidden_CrawlDepth
	}
	return 0
}

func (x *CrawlResult) GetResponseCode() int32 {
	if x != nil {
		return x.xxx_hidden_ResponseCode
	}
	return 0
}

func (x *CrawlResult) GetContentType() string {
	if x != nil {
		return x.xxx_hidden_ContentType
	}
	return ""
}

func (x *CrawlResult) GetContent() []byte {
	if x != nil {
		return x.xxx_hidden_Content
	}
	return nil
}

func (x *CrawlResult) GetResponseHeaders() []*HttpHeader {
	if x != nil {
		if x.xxx_hidden_ResponseHeaders != nil {
			return *x.xxx_hidden_ResponseHeaders
		}
	}
	return nil
}

func (x *CrawlResult) SetCrawlTarget(v *CrawlTarget) {
	x.xxx_hidden_CrawlTarget = v
}

func (x *CrawlResult) SetCrawlDepth(v int32) {
	x.xxx_hidden_CrawlDepth = v
}

func (x *CrawlResult) SetResponseCode(v int32) {
	x.xxx_hidden_ResponseCode = v
}

func (x *CrawlResult) SetContentType(v string) {
	x.xxx_hidden_ContentType = v
}

func (x *CrawlResult) SetContent(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Content = v
}

func (x *CrawlResult) SetResponseHeaders(v []*HttpHeader) {
	x.xxx_hidden_ResponseHeaders = &v
}

func (x *CrawlResult) HasCrawlTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CrawlTarget != nil
}

func (x *CrawlResult) ClearCrawlTarget() {
	x.xxx_hidden_CrawlTarget = nil
}

type CrawlResult_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The target visited by the crawler.
	CrawlTarget *CrawlTarget
	// Depth at which the target was visited.
	CrawlDepth int32
	// Response code from the crawled target.
	ResponseCode int32
	// Content type of the resource served at the crawl target.
	ContentType string
	// The content of the resource served at the crawl target.
	Content []byte
	// Http headers of the response
	ResponseHeaders []*HttpHeader
}

func (b0 CrawlResult_builder) Build() *CrawlResult {
	m0 := &CrawlResult{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_CrawlTarget = b.CrawlTarget
	x.xxx_hidden_CrawlDepth = b.CrawlDepth
	x.xxx_hidden_ResponseCode = b.ResponseCode
	x.xxx_hidden_ContentType = b.ContentType
	x.xxx_hidden_Content = b.Content
	x.xxx_hidden_ResponseHeaders = &b.ResponseHeaders
	return m0
}

// The crawler should only interact with web resources under certain scopes.
type CrawlConfig_Scope struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Domain string                 `protobuf:"bytes,1,opt,name=domain,proto3"`
	xxx_hidden_Path   string                 `protobuf:"bytes,2,opt,name=path,proto3"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *CrawlConfig_Scope) Reset() {
	*x = CrawlConfig_Scope{}
	mi := &file_web_crawl_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CrawlConfig_Scope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CrawlConfig_Scope) ProtoMessage() {}

func (x *CrawlConfig_Scope) ProtoReflect() protoreflect.Message {
	mi := &file_web_crawl_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *CrawlConfig_Scope) GetDomain() string {
	if x != nil {
		return x.xxx_hidden_Domain
	}
	return ""
}

func (x *CrawlConfig_Scope) GetPath() string {
	if x != nil {
		return x.xxx_hidden_Path
	}
	return ""
}

func (x *CrawlConfig_Scope) SetDomain(v string) {
	x.xxx_hidden_Domain = v
}

func (x *CrawlConfig_Scope) SetPath(v string) {
	x.xxx_hidden_Path = v
}

type CrawlConfig_Scope_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The domain of the scope, only URLs that are on the same domain or a
	// subdomain will be admitted for crawling. Domain might include a port.
	// Required.
	Domain string
	// The path of the scope, only URLs that are under the same path will be
	// admitted for crawling.
	// Optional. When empty, all URLs under the same domain are allowed,
	// regardless of the paths.
	Path string
}

func (b0 CrawlConfig_Scope_builder) Build() *CrawlConfig_Scope {
	m0 := &CrawlConfig_Scope{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Domain = b.Domain
	x.xxx_hidden_Path = b.Path
	return m0
}

var File_web_crawl_proto protoreflect.FileDescriptor

const file_web_crawl_proto_rawDesc = "" +
	"\n" +
	"\x0fweb_crawl.proto\x12\rtsunami.proto\x1a\rnetwork.proto\"\xca\x02\n" +
	"\vCrawlConfig\x12!\n" +
	"\fseeding_urls\x18\x01 \x03(\tR\vseedingUrls\x12\x1b\n" +
	"\tmax_depth\x18\x02 \x01(\x05R\bmaxDepth\x128\n" +
	"\x06scopes\x18\x03 \x03(\v2 .tsunami.proto.CrawlConfig.ScopeR\x06scopes\x12;\n" +
	"\x1ashould_enforce_scope_check\x18\x05 \x01(\bR\x17shouldEnforceScopeCheck\x12I\n" +
	"\x10network_endpoint\x18\x06 \x01(\v2\x1e.tsunami.proto.NetworkEndpointR\x0fnetworkEndpoint\x1a3\n" +
	"\x05Scope\x12\x16\n" +
	"\x06domain\x18\x01 \x01(\tR\x06domain\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04pathJ\x04\b\x04\x10\x05\"l\n" +
	"\vCrawlTarget\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x1f\n" +
	"\vhttp_method\x18\x02 \x01(\tR\n" +
	"httpMethod\x12*\n" +
	"\x11http_request_body\x18\x03 \x01(\fR\x0fhttpRequestBody\"4\n" +
	"\n" +
	"HttpHeader\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x95\x02\n" +
	"\vCrawlResult\x12=\n" +
	"\fcrawl_target\x18\x01 \x01(\v2\x1a.tsunami.proto.CrawlTargetR\vcrawlTarget\x12\x1f\n" +
	"\vcrawl_depth\x18\x02 \x01(\x05R\n" +
	"crawlDepth\x12#\n" +
	"\rresponse_code\x18\x03 \x01(\x05R\fresponseCode\x12!\n" +
	"\fcontent_type\x18\x04 \x01(\tR\vcontentType\x12\x18\n" +
	"\acontent\x18\x05 \x01(\fR\acontent\x12D\n" +
	"\x10response_headers\x18\x06 \x03(\v2\x19.tsunami.proto.HttpHeaderR\x0fresponseHeadersBt\n" +
	"\x18com.google.tsunami.protoB\x0eWebCrawlProtosP\x01ZFgithub.com/google/tsunami-security-scanner/proto/go/web_crawl_go_protob\x06proto3"

var file_web_crawl_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_web_crawl_proto_goTypes = []any{
	(*CrawlConfig)(nil),                      // 0: tsunami.proto.CrawlConfig
	(*CrawlTarget)(nil),                      // 1: tsunami.proto.CrawlTarget
	(*HttpHeader)(nil),                       // 2: tsunami.proto.HttpHeader
	(*CrawlResult)(nil),                      // 3: tsunami.proto.CrawlResult
	(*CrawlConfig_Scope)(nil),                // 4: tsunami.proto.CrawlConfig.Scope
	(*network_go_proto.NetworkEndpoint)(nil), // 5: tsunami.proto.NetworkEndpoint
}
var file_web_crawl_proto_depIdxs = []int32{
	4, // 0: tsunami.proto.CrawlConfig.scopes:type_name -> tsunami.proto.CrawlConfig.Scope
	5, // 1: tsunami.proto.CrawlConfig.network_endpoint:type_name -> tsunami.proto.NetworkEndpoint
	1, // 2: tsunami.proto.CrawlResult.crawl_target:type_name -> tsunami.proto.CrawlTarget
	2, // 3: tsunami.proto.CrawlResult.response_headers:type_name -> tsunami.proto.HttpHeader
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_web_crawl_proto_init() }
func file_web_crawl_proto_init() {
	if File_web_crawl_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_web_crawl_proto_rawDesc), len(file_web_crawl_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_web_crawl_proto_goTypes,
		DependencyIndexes: file_web_crawl_proto_depIdxs,
		MessageInfos:      file_web_crawl_proto_msgTypes,
	}.Build()
	File_web_crawl_proto = out.File
	file_web_crawl_proto_goTypes = nil
	file_web_crawl_proto_depIdxs = nil
}
