//
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Data models for describing a vulnerability detection report.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: detection.proto

package detection_go_proto

import (
	network_service_go_proto "github.com/google/tsunami-security-scanner/proto/go/network_service_go_proto"
	reconnaissance_go_proto "github.com/google/tsunami-security-scanner/proto/go/reconnaissance_go_proto"
	vulnerability_go_proto "github.com/google/tsunami-security-scanner/proto/go/vulnerability_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status of the vulnerability detection result.
type DetectionStatus int32

const (
	// Unspecified status.
	DetectionStatus_DETECTION_STATUS_UNSPECIFIED DetectionStatus = 0
	// Target is not vulnerable.
	DetectionStatus_SAFE DetectionStatus = 1
	// Target appears to be vulnerable (e.g. because running version is
	// vulnerable), but couldn't be verified.
	DetectionStatus_VULNERABILITY_PRESENT DetectionStatus = 2
	// Target is vulnerable and the detector successfully verified the
	// vulnerability.
	DetectionStatus_VULNERABILITY_VERIFIED DetectionStatus = 3
)

// Enum value maps for DetectionStatus.
var (
	DetectionStatus_name = map[int32]string{
		0: "DETECTION_STATUS_UNSPECIFIED",
		1: "SAFE",
		2: "VULNERABILITY_PRESENT",
		3: "VULNERABILITY_VERIFIED",
	}
	DetectionStatus_value = map[string]int32{
		"DETECTION_STATUS_UNSPECIFIED": 0,
		"SAFE":                         1,
		"VULNERABILITY_PRESENT":        2,
		"VULNERABILITY_VERIFIED":       3,
	}
)

func (x DetectionStatus) Enum() *DetectionStatus {
	p := new(DetectionStatus)
	*p = x
	return p
}

func (x DetectionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DetectionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_detection_proto_enumTypes[0].Descriptor()
}

func (DetectionStatus) Type() protoreflect.EnumType {
	return &file_detection_proto_enumTypes[0]
}

func (x DetectionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Full report about a detected vulnerability.
type DetectionReport struct {
	state                         protoimpl.MessageState                   `protogen:"opaque.v1"`
	xxx_hidden_TargetInfo         *reconnaissance_go_proto.TargetInfo      `protobuf:"bytes,1,opt,name=target_info,json=targetInfo,proto3"`
	xxx_hidden_NetworkService     *network_service_go_proto.NetworkService `protobuf:"bytes,2,opt,name=network_service,json=networkService,proto3"`
	xxx_hidden_DetectionTimestamp *timestamppb.Timestamp                   `protobuf:"bytes,3,opt,name=detection_timestamp,json=detectionTimestamp,proto3"`
	xxx_hidden_DetectionStatus    DetectionStatus                          `protobuf:"varint,4,opt,name=detection_status,json=detectionStatus,proto3,enum=tsunami.proto.DetectionStatus"`
	xxx_hidden_Vulnerability      *vulnerability_go_proto.Vulnerability    `protobuf:"bytes,5,opt,name=vulnerability,proto3"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *DetectionReport) Reset() {
	*x = DetectionReport{}
	mi := &file_detection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReport) ProtoMessage() {}

func (x *DetectionReport) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DetectionReport) GetTargetInfo() *reconnaissance_go_proto.TargetInfo {
	if x != nil {
		return x.xxx_hidden_TargetInfo
	}
	return nil
}

func (x *DetectionReport) GetNetworkService() *network_service_go_proto.NetworkService {
	if x != nil {
		return x.xxx_hidden_NetworkService
	}
	return nil
}

func (x *DetectionReport) GetDetectionTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DetectionTimestamp
	}
	return nil
}

func (x *DetectionReport) GetDetectionStatus() DetectionStatus {
	if x != nil {
		return x.xxx_hidden_DetectionStatus
	}
	return DetectionStatus_DETECTION_STATUS_UNSPECIFIED
}

func (x *DetectionReport) GetVulnerability() *vulnerability_go_proto.Vulnerability {
	if x != nil {
		return x.xxx_hidden_Vulnerability
	}
	return nil
}

func (x *DetectionReport) SetTargetInfo(v *reconnaissance_go_proto.TargetInfo) {
	x.xxx_hidden_TargetInfo = v
}

func (x *DetectionReport) SetNetworkService(v *network_service_go_proto.NetworkService) {
	x.xxx_hidden_NetworkService = v
}

func (x *DetectionReport) SetDetectionTimestamp(v *timestamppb.Timestamp) {
	x.xxx_hidden_DetectionTimestamp = v
}

func (x *DetectionReport) SetDetectionStatus(v DetectionStatus) {
	x.xxx_hidden_DetectionStatus = v
}

func (x *DetectionReport) SetVulnerability(v *vulnerability_go_proto.Vulnerability) {
	x.xxx_hidden_Vulnerability = v
}

func (x *DetectionReport) HasTargetInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TargetInfo != nil
}

func (x *DetectionReport) HasNetworkService() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NetworkService != nil
}

func (x *DetectionReport) HasDetectionTimestamp() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DetectionTimestamp != nil
}

func (x *DetectionReport) HasVulnerability() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Vulnerability != nil
}

func (x *DetectionReport) ClearTargetInfo() {
	x.xxx_hidden_TargetInfo = nil
}

func (x *DetectionReport) ClearNetworkService() {
	x.xxx_hidden_NetworkService = nil
}

func (x *DetectionReport) ClearDetectionTimestamp() {
	x.xxx_hidden_DetectionTimestamp = nil
}

func (x *DetectionReport) ClearVulnerability() {
	x.xxx_hidden_Vulnerability = nil
}

type DetectionReport_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Information about the scanned target.
	TargetInfo *reconnaissance_go_proto.TargetInfo
	// Information about the scanned network service.
	NetworkService *network_service_go_proto.NetworkService
	// Time when the vulnerability was detected.
	DetectionTimestamp *timestamppb.Timestamp
	// Status of the detection result.
	DetectionStatus DetectionStatus
	// Full details about the detected vulnerability.
	Vulnerability *vulnerability_go_proto.Vulnerability
}

func (b0 DetectionReport_builder) Build() *DetectionReport {
	m0 := &DetectionReport{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TargetInfo = b.TargetInfo
	x.xxx_hidden_NetworkService = b.NetworkService
	x.xxx_hidden_DetectionTimestamp = b.DetectionTimestamp
	x.xxx_hidden_DetectionStatus = b.DetectionStatus
	x.xxx_hidden_Vulnerability = b.Vulnerability
	return m0
}

type DetectionReportList struct {
	state                       protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_DetectionReports *[]*DetectionReport    `protobuf:"bytes,1,rep,name=detection_reports,json=detectionReports,proto3"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *DetectionReportList) Reset() {
	*x = DetectionReportList{}
	mi := &file_detection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DetectionReportList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DetectionReportList) ProtoMessage() {}

func (x *DetectionReportList) ProtoReflect() protoreflect.Message {
	mi := &file_detection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DetectionReportList) GetDetectionReports() []*DetectionReport {
	if x != nil {
		if x.xxx_hidden_DetectionReports != nil {
			return *x.xxx_hidden_DetectionReports
		}
	}
	return nil
}

func (x *DetectionReportList) SetDetectionReports(v []*DetectionReport) {
	x.xxx_hidden_DetectionReports = &v
}

type DetectionReportList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	DetectionReports []*DetectionReport
}

func (b0 DetectionReportList_builder) Build() *DetectionReportList {
	m0 := &DetectionReportList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_DetectionReports = &b.DetectionReports
	return m0
}

var File_detection_proto protoreflect.FileDescriptor

const file_detection_proto_rawDesc = "" +
	"\n" +
	"\x0fdetection.proto\x12\rtsunami.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x15network_service.proto\x1a\x14reconnaissance.proto\x1a\x13vulnerability.proto\"\xf1\x02\n" +
	"\x0fDetectionReport\x12:\n" +
	"\vtarget_info\x18\x01 \x01(\v2\x19.tsunami.proto.TargetInfoR\n" +
	"targetInfo\x12F\n" +
	"\x0fnetwork_service\x18\x02 \x01(\v2\x1d.tsunami.proto.NetworkServiceR\x0enetworkService\x12K\n" +
	"\x13detection_timestamp\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x12detectionTimestamp\x12I\n" +
	"\x10detection_status\x18\x04 \x01(\x0e2\x1e.tsunami.proto.DetectionStatusR\x0fdetectionStatus\x12B\n" +
	"\rvulnerability\x18\x05 \x01(\v2\x1c.tsunami.proto.VulnerabilityR\rvulnerability\"b\n" +
	"\x13DetectionReportList\x12K\n" +
	"\x11detection_reports\x18\x01 \x03(\v2\x1e.tsunami.proto.DetectionReportR\x10detectionReports*t\n" +
	"\x0fDetectionStatus\x12 \n" +
	"\x1cDETECTION_STATUS_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04SAFE\x10\x01\x12\x19\n" +
	"\x15VULNERABILITY_PRESENT\x10\x02\x12\x1a\n" +
	"\x16VULNERABILITY_VERIFIED\x10\x03Bu\n" +
	"\x18com.google.tsunami.protoB\x0fDetectionProtosP\x01ZFgithub.com/google/tsunami-security-scanner/proto/go/detection_go_protob\x06proto3"

var file_detection_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_detection_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_detection_proto_goTypes = []any{
	(DetectionStatus)(0),                            // 0: tsunami.proto.DetectionStatus
	(*DetectionReport)(nil),                         // 1: tsunami.proto.DetectionReport
	(*DetectionReportList)(nil),                     // 2: tsunami.proto.DetectionReportList
	(*reconnaissance_go_proto.TargetInfo)(nil),      // 3: tsunami.proto.TargetInfo
	(*network_service_go_proto.NetworkService)(nil), // 4: tsunami.proto.NetworkService
	(*timestamppb.Timestamp)(nil),                   // 5: google.protobuf.Timestamp
	(*vulnerability_go_proto.Vulnerability)(nil),    // 6: tsunami.proto.Vulnerability
}
var file_detection_proto_depIdxs = []int32{
	3, // 0: tsunami.proto.DetectionReport.target_info:type_name -> tsunami.proto.TargetInfo
	4, // 1: tsunami.proto.DetectionReport.network_service:type_name -> tsunami.proto.NetworkService
	5, // 2: tsunami.proto.DetectionReport.detection_timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: tsunami.proto.DetectionReport.detection_status:type_name -> tsunami.proto.DetectionStatus
	6, // 4: tsunami.proto.DetectionReport.vulnerability:type_name -> tsunami.proto.Vulnerability
	1, // 5: tsunami.proto.DetectionReportList.detection_reports:type_name -> tsunami.proto.DetectionReport
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_detection_proto_init() }
func file_detection_proto_init() {
	if File_detection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_detection_proto_rawDesc), len(file_detection_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_detection_proto_goTypes,
		DependencyIndexes: file_detection_proto_depIdxs,
		EnumInfos:         file_detection_proto_enumTypes,
		MessageInfos:      file_detection_proto_msgTypes,
	}.Build()
	File_detection_proto = out.File
	file_detection_proto_goTypes = nil
	file_detection_proto_depIdxs = nil
}
