//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Data models utilized by the Tsunami Paylaod Generator

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: payload_generator.proto

package payload_generator_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayloadValidationType int32

const (
	PayloadValidationType_VALIDATION_TYPE_UNSPECIFIED PayloadValidationType = 0
	PayloadValidationType_VALIDATION_REGEX            PayloadValidationType = 1
)

// Enum value maps for PayloadValidationType.
var (
	PayloadValidationType_name = map[int32]string{
		0: "VALIDATION_TYPE_UNSPECIFIED",
		1: "VALIDATION_REGEX",
	}
	PayloadValidationType_value = map[string]int32{
		"VALIDATION_TYPE_UNSPECIFIED": 0,
		"VALIDATION_REGEX":            1,
	}
)

func (x PayloadValidationType) Enum() *PayloadValidationType {
	p := new(PayloadValidationType)
	*p = x
	return p
}

func (x PayloadValidationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadValidationType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_generator_proto_enumTypes[0].Descriptor()
}

func (PayloadValidationType) Type() protoreflect.EnumType {
	return &file_payload_generator_proto_enumTypes[0]
}

func (x PayloadValidationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The type of vulnerability the detector is looking for
type PayloadGeneratorConfig_VulnerabilityType int32

const (
	// Unspecified vulnerability type
	PayloadGeneratorConfig_VULNERABILITY_TYPE_UNSPECIFIED PayloadGeneratorConfig_VulnerabilityType = 0
	// RCE which returns the output of the execution
	PayloadGeneratorConfig_REFLECTIVE_RCE PayloadGeneratorConfig_VulnerabilityType = 1
	// RCE which does not return the output of the execution
	PayloadGeneratorConfig_BLIND_RCE PayloadGeneratorConfig_VulnerabilityType = 2
	// Server-Side Request Forgery
	PayloadGeneratorConfig_SSRF PayloadGeneratorConfig_VulnerabilityType = 3
	// Arbitrary File Write
	PayloadGeneratorConfig_ARBITRARY_FILE_WRITE PayloadGeneratorConfig_VulnerabilityType = 4
	// RCE without output of the execution + File Read (needed to get
	// confirmation string)
	PayloadGeneratorConfig_BLIND_RCE_FILE_READ PayloadGeneratorConfig_VulnerabilityType = 5
)

// Enum value maps for PayloadGeneratorConfig_VulnerabilityType.
var (
	PayloadGeneratorConfig_VulnerabilityType_name = map[int32]string{
		0: "VULNERABILITY_TYPE_UNSPECIFIED",
		1: "REFLECTIVE_RCE",
		2: "BLIND_RCE",
		3: "SSRF",
		4: "ARBITRARY_FILE_WRITE",
		5: "BLIND_RCE_FILE_READ",
	}
	PayloadGeneratorConfig_VulnerabilityType_value = map[string]int32{
		"VULNERABILITY_TYPE_UNSPECIFIED": 0,
		"REFLECTIVE_RCE":                 1,
		"BLIND_RCE":                      2,
		"SSRF":                           3,
		"ARBITRARY_FILE_WRITE":           4,
		"BLIND_RCE_FILE_READ":            5,
	}
)

func (x PayloadGeneratorConfig_VulnerabilityType) Enum() *PayloadGeneratorConfig_VulnerabilityType {
	p := new(PayloadGeneratorConfig_VulnerabilityType)
	*p = x
	return p
}

func (x PayloadGeneratorConfig_VulnerabilityType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadGeneratorConfig_VulnerabilityType) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_generator_proto_enumTypes[1].Descriptor()
}

func (PayloadGeneratorConfig_VulnerabilityType) Type() protoreflect.EnumType {
	return &file_payload_generator_proto_enumTypes[1]
}

func (x PayloadGeneratorConfig_VulnerabilityType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The environment that processes the payload for execution e.g. a PHP-based
// target likely wants a payload that is itself PHP code.
type PayloadGeneratorConfig_InterpretationEnvironment int32

const (
	// Unspecified interpretation environment type
	PayloadGeneratorConfig_INTERPRETATION_ENVIRONMENT_UNSPECIFIED PayloadGeneratorConfig_InterpretationEnvironment = 0
	// Payload is interpreted within a Linux shell environment
	PayloadGeneratorConfig_LINUX_SHELL PayloadGeneratorConfig_InterpretationEnvironment = 1
	// Payload is interpreted wihin a Java compiler context
	PayloadGeneratorConfig_JAVA PayloadGeneratorConfig_InterpretationEnvironment = 2
	// Payload is interpreted wihin a PHP VM context
	PayloadGeneratorConfig_PHP PayloadGeneratorConfig_InterpretationEnvironment = 3
	// Interpretation environment doesn't matter
	PayloadGeneratorConfig_INTERPRETATION_ANY PayloadGeneratorConfig_InterpretationEnvironment = 4
	// Payload is interpreted wihin crontab
	PayloadGeneratorConfig_LINUX_ROOT_CRONTAB PayloadGeneratorConfig_InterpretationEnvironment = 5
	// Payload is interpreted wihin a Windows shell environment
	PayloadGeneratorConfig_WINDOWS_SHELL PayloadGeneratorConfig_InterpretationEnvironment = 6
	// Payload is interpreted within a JSP shell environment
	PayloadGeneratorConfig_JSP PayloadGeneratorConfig_InterpretationEnvironment = 7
)

// Enum value maps for PayloadGeneratorConfig_InterpretationEnvironment.
var (
	PayloadGeneratorConfig_InterpretationEnvironment_name = map[int32]string{
		0: "INTERPRETATION_ENVIRONMENT_UNSPECIFIED",
		1: "LINUX_SHELL",
		2: "JAVA",
		3: "PHP",
		4: "INTERPRETATION_ANY",
		5: "LINUX_ROOT_CRONTAB",
		6: "WINDOWS_SHELL",
		7: "JSP",
	}
	PayloadGeneratorConfig_InterpretationEnvironment_value = map[string]int32{
		"INTERPRETATION_ENVIRONMENT_UNSPECIFIED": 0,
		"LINUX_SHELL":                            1,
		"JAVA":                                   2,
		"PHP":                                    3,
		"INTERPRETATION_ANY":                     4,
		"LINUX_ROOT_CRONTAB":                     5,
		"WINDOWS_SHELL":                          6,
		"JSP":                                    7,
	}
)

func (x PayloadGeneratorConfig_InterpretationEnvironment) Enum() *PayloadGeneratorConfig_InterpretationEnvironment {
	p := new(PayloadGeneratorConfig_InterpretationEnvironment)
	*p = x
	return p
}

func (x PayloadGeneratorConfig_InterpretationEnvironment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadGeneratorConfig_InterpretationEnvironment) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_generator_proto_enumTypes[2].Descriptor()
}

func (PayloadGeneratorConfig_InterpretationEnvironment) Type() protoreflect.EnumType {
	return &file_payload_generator_proto_enumTypes[2]
}

func (x PayloadGeneratorConfig_InterpretationEnvironment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The actual runtime environment when the payload is run e.g. while a
// PHP-based target wants a PHP-interpretation environment, the actual code
// execution may happen via the Linux shell: exec(“echo \”this is running in
// the system.\””).
type PayloadGeneratorConfig_ExecutionEnvironment int32

const (
	// Unspecified execution environment type
	PayloadGeneratorConfig_EXECUTION_ENVIRONMENT_UNSPECIFIED PayloadGeneratorConfig_ExecutionEnvironment = 0
	// Execute within the InterpretationEnvironment
	PayloadGeneratorConfig_EXEC_INTERPRETATION_ENVIRONMENT PayloadGeneratorConfig_ExecutionEnvironment = 1
	// Execution environment doesn't matter
	PayloadGeneratorConfig_EXEC_ANY PayloadGeneratorConfig_ExecutionEnvironment = 2
)

// Enum value maps for PayloadGeneratorConfig_ExecutionEnvironment.
var (
	PayloadGeneratorConfig_ExecutionEnvironment_name = map[int32]string{
		0: "EXECUTION_ENVIRONMENT_UNSPECIFIED",
		1: "EXEC_INTERPRETATION_ENVIRONMENT",
		2: "EXEC_ANY",
	}
	PayloadGeneratorConfig_ExecutionEnvironment_value = map[string]int32{
		"EXECUTION_ENVIRONMENT_UNSPECIFIED": 0,
		"EXEC_INTERPRETATION_ENVIRONMENT":   1,
		"EXEC_ANY":                          2,
	}
)

func (x PayloadGeneratorConfig_ExecutionEnvironment) Enum() *PayloadGeneratorConfig_ExecutionEnvironment {
	p := new(PayloadGeneratorConfig_ExecutionEnvironment)
	*p = x
	return p
}

func (x PayloadGeneratorConfig_ExecutionEnvironment) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PayloadGeneratorConfig_ExecutionEnvironment) Descriptor() protoreflect.EnumDescriptor {
	return file_payload_generator_proto_enumTypes[3].Descriptor()
}

func (PayloadGeneratorConfig_ExecutionEnvironment) Type() protoreflect.EnumType {
	return &file_payload_generator_proto_enumTypes[3]
}

func (x PayloadGeneratorConfig_ExecutionEnvironment) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Attributes utilized by the PayloadGenerator to select a payload
type PayloadGeneratorConfig struct {
	state                                protoimpl.MessageState                           `protogen:"opaque.v1"`
	xxx_hidden_VulnerabilityType         PayloadGeneratorConfig_VulnerabilityType         `protobuf:"varint,2,opt,name=vulnerability_type,json=vulnerabilityType,proto3,enum=tsunami.proto.PayloadGeneratorConfig_VulnerabilityType"`
	xxx_hidden_InterpretationEnvironment PayloadGeneratorConfig_InterpretationEnvironment `protobuf:"varint,3,opt,name=interpretation_environment,json=interpretationEnvironment,proto3,enum=tsunami.proto.PayloadGeneratorConfig_InterpretationEnvironment"`
	xxx_hidden_ExecutionEnvironment      PayloadGeneratorConfig_ExecutionEnvironment      `protobuf:"varint,4,opt,name=execution_environment,json=executionEnvironment,proto3,enum=tsunami.proto.PayloadGeneratorConfig_ExecutionEnvironment"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *PayloadGeneratorConfig) Reset() {
	*x = PayloadGeneratorConfig{}
	mi := &file_payload_generator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadGeneratorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadGeneratorConfig) ProtoMessage() {}

func (x *PayloadGeneratorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_payload_generator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PayloadGeneratorConfig) GetVulnerabilityType() PayloadGeneratorConfig_VulnerabilityType {
	if x != nil {
		return x.xxx_hidden_VulnerabilityType
	}
	return PayloadGeneratorConfig_VULNERABILITY_TYPE_UNSPECIFIED
}

func (x *PayloadGeneratorConfig) GetInterpretationEnvironment() PayloadGeneratorConfig_InterpretationEnvironment {
	if x != nil {
		return x.xxx_hidden_InterpretationEnvironment
	}
	return PayloadGeneratorConfig_INTERPRETATION_ENVIRONMENT_UNSPECIFIED
}

func (x *PayloadGeneratorConfig) GetExecutionEnvironment() PayloadGeneratorConfig_ExecutionEnvironment {
	if x != nil {
		return x.xxx_hidden_ExecutionEnvironment
	}
	return PayloadGeneratorConfig_EXECUTION_ENVIRONMENT_UNSPECIFIED
}

func (x *PayloadGeneratorConfig) SetVulnerabilityType(v PayloadGeneratorConfig_VulnerabilityType) {
	x.xxx_hidden_VulnerabilityType = v
}

func (x *PayloadGeneratorConfig) SetInterpretationEnvironment(v PayloadGeneratorConfig_InterpretationEnvironment) {
	x.xxx_hidden_InterpretationEnvironment = v
}

func (x *PayloadGeneratorConfig) SetExecutionEnvironment(v PayloadGeneratorConfig_ExecutionEnvironment) {
	x.xxx_hidden_ExecutionEnvironment = v
}

type PayloadGeneratorConfig_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	VulnerabilityType         PayloadGeneratorConfig_VulnerabilityType
	InterpretationEnvironment PayloadGeneratorConfig_InterpretationEnvironment
	ExecutionEnvironment      PayloadGeneratorConfig_ExecutionEnvironment
}

func (b0 PayloadGeneratorConfig_builder) Build() *PayloadGeneratorConfig {
	m0 := &PayloadGeneratorConfig{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_VulnerabilityType = b.VulnerabilityType
	x.xxx_hidden_InterpretationEnvironment = b.InterpretationEnvironment
	x.xxx_hidden_ExecutionEnvironment = b.ExecutionEnvironment
	return m0
}

// Attributes of a payload. A detector can check these attributes to change its
// logic based on the payload type.
type PayloadAttributes struct {
	state                         protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_UsesCallbackServer bool                   `protobuf:"varint,1,opt,name=uses_callback_server,json=usesCallbackServer,proto3"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *PayloadAttributes) Reset() {
	*x = PayloadAttributes{}
	mi := &file_payload_generator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadAttributes) ProtoMessage() {}

func (x *PayloadAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_payload_generator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PayloadAttributes) GetUsesCallbackServer() bool {
	if x != nil {
		return x.xxx_hidden_UsesCallbackServer
	}
	return false
}

func (x *PayloadAttributes) SetUsesCallbackServer(v bool) {
	x.xxx_hidden_UsesCallbackServer = v
}

type PayloadAttributes_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Whether the payload uses the callback server
	UsesCallbackServer bool
}

func (b0 PayloadAttributes_builder) Build() *PayloadAttributes {
	m0 := &PayloadAttributes{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_UsesCallbackServer = b.UsesCallbackServer
	return m0
}

// Container type for payload_definitions.yaml
type PayloadLibrary struct {
	state               protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Payloads *[]*PayloadDefinition  `protobuf:"bytes,1,rep,name=payloads,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PayloadLibrary) Reset() {
	*x = PayloadLibrary{}
	mi := &file_payload_generator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadLibrary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadLibrary) ProtoMessage() {}

func (x *PayloadLibrary) ProtoReflect() protoreflect.Message {
	mi := &file_payload_generator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PayloadLibrary) GetPayloads() []*PayloadDefinition {
	if x != nil {
		if x.xxx_hidden_Payloads != nil {
			return *x.xxx_hidden_Payloads
		}
	}
	return nil
}

func (x *PayloadLibrary) SetPayloads(v []*PayloadDefinition) {
	x.xxx_hidden_Payloads = &v
}

type PayloadLibrary_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Payloads []*PayloadDefinition
}

func (b0 PayloadLibrary_builder) Build() *PayloadLibrary {
	m0 := &PayloadLibrary{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Payloads = &b.Payloads
	return m0
}

// Schema for each entry in payload_definitions.yaml
// Note: this message uses StringValue and BoolValue because we validate whether
// each payload definition in the yaml file has the correct fields present.
// Since empty proto fields are given default values (proto fields are not
// nullable), we use the wrapped types to check for actual presence.
type PayloadDefinition struct {
	state                                protoimpl.MessageState                           `protogen:"opaque.v1"`
	xxx_hidden_Name                      *wrapperspb.StringValue                          `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_InterpretationEnvironment PayloadGeneratorConfig_InterpretationEnvironment `protobuf:"varint,2,opt,name=interpretation_environment,json=interpretationEnvironment,proto3,enum=tsunami.proto.PayloadGeneratorConfig_InterpretationEnvironment"`
	xxx_hidden_ExecutionEnvironment      PayloadGeneratorConfig_ExecutionEnvironment      `protobuf:"varint,3,opt,name=execution_environment,json=executionEnvironment,proto3,enum=tsunami.proto.PayloadGeneratorConfig_ExecutionEnvironment"`
	xxx_hidden_VulnerabilityType         []PayloadGeneratorConfig_VulnerabilityType       `protobuf:"varint,4,rep,packed,name=vulnerability_type,json=vulnerabilityType,proto3,enum=tsunami.proto.PayloadGeneratorConfig_VulnerabilityType"`
	xxx_hidden_UsesCallbackServer        *wrapperspb.BoolValue                            `protobuf:"bytes,5,opt,name=uses_callback_server,json=usesCallbackServer,proto3"`
	xxx_hidden_PayloadString             *wrapperspb.StringValue                          `protobuf:"bytes,6,opt,name=payload_string,json=payloadString,proto3"`
	xxx_hidden_ValidationType            PayloadValidationType                            `protobuf:"varint,7,opt,name=validation_type,json=validationType,proto3,enum=tsunami.proto.PayloadValidationType"`
	xxx_hidden_ValidationRegex           *wrapperspb.StringValue                          `protobuf:"bytes,8,opt,name=validation_regex,json=validationRegex,proto3"`
	unknownFields                        protoimpl.UnknownFields
	sizeCache                            protoimpl.SizeCache
}

func (x *PayloadDefinition) Reset() {
	*x = PayloadDefinition{}
	mi := &file_payload_generator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PayloadDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayloadDefinition) ProtoMessage() {}

func (x *PayloadDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_payload_generator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PayloadDefinition) GetName() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return nil
}

func (x *PayloadDefinition) GetInterpretationEnvironment() PayloadGeneratorConfig_InterpretationEnvironment {
	if x != nil {
		return x.xxx_hidden_InterpretationEnvironment
	}
	return PayloadGeneratorConfig_INTERPRETATION_ENVIRONMENT_UNSPECIFIED
}

func (x *PayloadDefinition) GetExecutionEnvironment() PayloadGeneratorConfig_ExecutionEnvironment {
	if x != nil {
		return x.xxx_hidden_ExecutionEnvironment
	}
	return PayloadGeneratorConfig_EXECUTION_ENVIRONMENT_UNSPECIFIED
}

func (x *PayloadDefinition) GetVulnerabilityType() []PayloadGeneratorConfig_VulnerabilityType {
	if x != nil {
		return x.xxx_hidden_VulnerabilityType
	}
	return nil
}

func (x *PayloadDefinition) GetUsesCallbackServer() *wrapperspb.BoolValue {
	if x != nil {
		return x.xxx_hidden_UsesCallbackServer
	}
	return nil
}

func (x *PayloadDefinition) GetPayloadString() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_PayloadString
	}
	return nil
}

func (x *PayloadDefinition) GetValidationType() PayloadValidationType {
	if x != nil {
		return x.xxx_hidden_ValidationType
	}
	return PayloadValidationType_VALIDATION_TYPE_UNSPECIFIED
}

func (x *PayloadDefinition) GetValidationRegex() *wrapperspb.StringValue {
	if x != nil {
		return x.xxx_hidden_ValidationRegex
	}
	return nil
}

func (x *PayloadDefinition) SetName(v *wrapperspb.StringValue) {
	x.xxx_hidden_Name = v
}

func (x *PayloadDefinition) SetInterpretationEnvironment(v PayloadGeneratorConfig_InterpretationEnvironment) {
	x.xxx_hidden_InterpretationEnvironment = v
}

func (x *PayloadDefinition) SetExecutionEnvironment(v PayloadGeneratorConfig_ExecutionEnvironment) {
	x.xxx_hidden_ExecutionEnvironment = v
}

func (x *PayloadDefinition) SetVulnerabilityType(v []PayloadGeneratorConfig_VulnerabilityType) {
	x.xxx_hidden_VulnerabilityType = v
}

func (x *PayloadDefinition) SetUsesCallbackServer(v *wrapperspb.BoolValue) {
	x.xxx_hidden_UsesCallbackServer = v
}

func (x *PayloadDefinition) SetPayloadString(v *wrapperspb.StringValue) {
	x.xxx_hidden_PayloadString = v
}

func (x *PayloadDefinition) SetValidationType(v PayloadValidationType) {
	x.xxx_hidden_ValidationType = v
}

func (x *PayloadDefinition) SetValidationRegex(v *wrapperspb.StringValue) {
	x.xxx_hidden_ValidationRegex = v
}

func (x *PayloadDefinition) HasName() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Name != nil
}

func (x *PayloadDefinition) HasUsesCallbackServer() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UsesCallbackServer != nil
}

func (x *PayloadDefinition) HasPayloadString() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_PayloadString != nil
}

func (x *PayloadDefinition) HasValidationRegex() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ValidationRegex != nil
}

func (x *PayloadDefinition) ClearName() {
	x.xxx_hidden_Name = nil
}

func (x *PayloadDefinition) ClearUsesCallbackServer() {
	x.xxx_hidden_UsesCallbackServer = nil
}

func (x *PayloadDefinition) ClearPayloadString() {
	x.xxx_hidden_PayloadString = nil
}

func (x *PayloadDefinition) ClearValidationRegex() {
	x.xxx_hidden_ValidationRegex = nil
}

type PayloadDefinition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The human-readable string to identify the payload
	Name                      *wrapperspb.StringValue
	InterpretationEnvironment PayloadGeneratorConfig_InterpretationEnvironment
	ExecutionEnvironment      PayloadGeneratorConfig_ExecutionEnvironment
	// All vulnerability types this payload can be used for
	VulnerabilityType []PayloadGeneratorConfig_VulnerabilityType
	// If true, payload_string must contain the $TSUNAMI_PAYLOAD_TOKEN_URL
	// token. Validation will automatically check against the callback server, so
	// the validation* fields do not need to be set.
	UsesCallbackServer *wrapperspb.BoolValue
	// The actual payload command string. The following special tokens can be
	// used which will cause the framework to inject dynamic content into the
	// command:
	// - $TSUNAMI_PAYLOAD_TOKEN_URL: url for the callback server
	// - a random string, used to reduce false positives.
	PayloadString *wrapperspb.StringValue
	// The type of validation function for determining if the payload was
	// executed. Currently, only REGEX is supported.
	ValidationType PayloadValidationType
	// Required if validation_type == REGEX. Must be compatible with
	// java.util.regex.Pattern. The string will first be preprocessed before
	// applied as a regex, replacing any of the following tokens with the
	// corresponding values supplied by the framework:
	//   - $TSUNAMI_PAYLOAD_TOKEN_RANDOM: a random string, used to reduce false
	//     positives. The value is guaranteed to be the same as the value supplied
	//     to payload_string.
	ValidationRegex *wrapperspb.StringValue
}

func (b0 PayloadDefinition_builder) Build() *PayloadDefinition {
	m0 := &PayloadDefinition{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_InterpretationEnvironment = b.InterpretationEnvironment
	x.xxx_hidden_ExecutionEnvironment = b.ExecutionEnvironment
	x.xxx_hidden_VulnerabilityType = b.VulnerabilityType
	x.xxx_hidden_UsesCallbackServer = b.UsesCallbackServer
	x.xxx_hidden_PayloadString = b.PayloadString
	x.xxx_hidden_ValidationType = b.ValidationType
	x.xxx_hidden_ValidationRegex = b.ValidationRegex
	return m0
}

var File_payload_generator_proto protoreflect.FileDescriptor

const file_payload_generator_proto_rawDesc = "" +
	"\n" +
	"\x17payload_generator.proto\x12\rtsunami.proto\x1a\x1egoogle/protobuf/wrappers.proto\"\xb7\x06\n" +
	"\x16PayloadGeneratorConfig\x12f\n" +
	"\x12vulnerability_type\x18\x02 \x01(\x0e27.tsunami.proto.PayloadGeneratorConfig.VulnerabilityTypeR\x11vulnerabilityType\x12~\n" +
	"\x1ainterpretation_environment\x18\x03 \x01(\x0e2?.tsunami.proto.PayloadGeneratorConfig.InterpretationEnvironmentR\x19interpretationEnvironment\x12o\n" +
	"\x15execution_environment\x18\x04 \x01(\x0e2:.tsunami.proto.PayloadGeneratorConfig.ExecutionEnvironmentR\x14executionEnvironment\"\x97\x01\n" +
	"\x11VulnerabilityType\x12\"\n" +
	"\x1eVULNERABILITY_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eREFLECTIVE_RCE\x10\x01\x12\r\n" +
	"\tBLIND_RCE\x10\x02\x12\b\n" +
	"\x04SSRF\x10\x03\x12\x18\n" +
	"\x14ARBITRARY_FILE_WRITE\x10\x04\x12\x17\n" +
	"\x13BLIND_RCE_FILE_READ\x10\x05\"\xb7\x01\n" +
	"\x19InterpretationEnvironment\x12*\n" +
	"&INTERPRETATION_ENVIRONMENT_UNSPECIFIED\x10\x00\x12\x0f\n" +
	"\vLINUX_SHELL\x10\x01\x12\b\n" +
	"\x04JAVA\x10\x02\x12\a\n" +
	"\x03PHP\x10\x03\x12\x16\n" +
	"\x12INTERPRETATION_ANY\x10\x04\x12\x16\n" +
	"\x12LINUX_ROOT_CRONTAB\x10\x05\x12\x11\n" +
	"\rWINDOWS_SHELL\x10\x06\x12\a\n" +
	"\x03JSP\x10\a\"p\n" +
	"\x14ExecutionEnvironment\x12%\n" +
	"!EXECUTION_ENVIRONMENT_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fEXEC_INTERPRETATION_ENVIRONMENT\x10\x01\x12\f\n" +
	"\bEXEC_ANY\x10\x02\"E\n" +
	"\x11PayloadAttributes\x120\n" +
	"\x14uses_callback_server\x18\x01 \x01(\bR\x12usesCallbackServer\"N\n" +
	"\x0ePayloadLibrary\x12<\n" +
	"\bpayloads\x18\x01 \x03(\v2 .tsunami.proto.PayloadDefinitionR\bpayloads\"\xc9\x05\n" +
	"\x11PayloadDefinition\x120\n" +
	"\x04name\x18\x01 \x01(\v2\x1c.google.protobuf.StringValueR\x04name\x12~\n" +
	"\x1ainterpretation_environment\x18\x02 \x01(\x0e2?.tsunami.proto.PayloadGeneratorConfig.InterpretationEnvironmentR\x19interpretationEnvironment\x12o\n" +
	"\x15execution_environment\x18\x03 \x01(\x0e2:.tsunami.proto.PayloadGeneratorConfig.ExecutionEnvironmentR\x14executionEnvironment\x12f\n" +
	"\x12vulnerability_type\x18\x04 \x03(\x0e27.tsunami.proto.PayloadGeneratorConfig.VulnerabilityTypeR\x11vulnerabilityType\x12L\n" +
	"\x14uses_callback_server\x18\x05 \x01(\v2\x1a.google.protobuf.BoolValueR\x12usesCallbackServer\x12C\n" +
	"\x0epayload_string\x18\x06 \x01(\v2\x1c.google.protobuf.StringValueR\rpayloadString\x12M\n" +
	"\x0fvalidation_type\x18\a \x01(\x0e2$.tsunami.proto.PayloadValidationTypeR\x0evalidationType\x12G\n" +
	"\x10validation_regex\x18\b \x01(\v2\x1c.google.protobuf.StringValueR\x0fvalidationRegex*N\n" +
	"\x15PayloadValidationType\x12\x1f\n" +
	"\x1bVALIDATION_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10VALIDATION_REGEX\x10\x01B\x84\x01\n" +
	"\x18com.google.tsunami.protoB\x16PayloadGeneratorProtosP\x01ZNgithub.com/google/tsunami-security-scanner/proto/go/payload_generator_go_protob\x06proto3"

var file_payload_generator_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_payload_generator_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_payload_generator_proto_goTypes = []any{
	(PayloadValidationType)(0),                            // 0: tsunami.proto.PayloadValidationType
	(PayloadGeneratorConfig_VulnerabilityType)(0),         // 1: tsunami.proto.PayloadGeneratorConfig.VulnerabilityType
	(PayloadGeneratorConfig_InterpretationEnvironment)(0), // 2: tsunami.proto.PayloadGeneratorConfig.InterpretationEnvironment
	(PayloadGeneratorConfig_ExecutionEnvironment)(0),      // 3: tsunami.proto.PayloadGeneratorConfig.ExecutionEnvironment
	(*PayloadGeneratorConfig)(nil),                        // 4: tsunami.proto.PayloadGeneratorConfig
	(*PayloadAttributes)(nil),                             // 5: tsunami.proto.PayloadAttributes
	(*PayloadLibrary)(nil),                                // 6: tsunami.proto.PayloadLibrary
	(*PayloadDefinition)(nil),                             // 7: tsunami.proto.PayloadDefinition
	(*wrapperspb.StringValue)(nil),                        // 8: google.protobuf.StringValue
	(*wrapperspb.BoolValue)(nil),                          // 9: google.protobuf.BoolValue
}
var file_payload_generator_proto_depIdxs = []int32{
	1,  // 0: tsunami.proto.PayloadGeneratorConfig.vulnerability_type:type_name -> tsunami.proto.PayloadGeneratorConfig.VulnerabilityType
	2,  // 1: tsunami.proto.PayloadGeneratorConfig.interpretation_environment:type_name -> tsunami.proto.PayloadGeneratorConfig.InterpretationEnvironment
	3,  // 2: tsunami.proto.PayloadGeneratorConfig.execution_environment:type_name -> tsunami.proto.PayloadGeneratorConfig.ExecutionEnvironment
	7,  // 3: tsunami.proto.PayloadLibrary.payloads:type_name -> tsunami.proto.PayloadDefinition
	8,  // 4: tsunami.proto.PayloadDefinition.name:type_name -> google.protobuf.StringValue
	2,  // 5: tsunami.proto.PayloadDefinition.interpretation_environment:type_name -> tsunami.proto.PayloadGeneratorConfig.InterpretationEnvironment
	3,  // 6: tsunami.proto.PayloadDefinition.execution_environment:type_name -> tsunami.proto.PayloadGeneratorConfig.ExecutionEnvironment
	1,  // 7: tsunami.proto.PayloadDefinition.vulnerability_type:type_name -> tsunami.proto.PayloadGeneratorConfig.VulnerabilityType
	9,  // 8: tsunami.proto.PayloadDefinition.uses_callback_server:type_name -> google.protobuf.BoolValue
	8,  // 9: tsunami.proto.PayloadDefinition.payload_string:type_name -> google.protobuf.StringValue
	0,  // 10: tsunami.proto.PayloadDefinition.validation_type:type_name -> tsunami.proto.PayloadValidationType
	8,  // 11: tsunami.proto.PayloadDefinition.validation_regex:type_name -> google.protobuf.StringValue
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_payload_generator_proto_init() }
func file_payload_generator_proto_init() {
	if File_payload_generator_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_payload_generator_proto_rawDesc), len(file_payload_generator_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payload_generator_proto_goTypes,
		DependencyIndexes: file_payload_generator_proto_depIdxs,
		EnumInfos:         file_payload_generator_proto_enumTypes,
		MessageInfos:      file_payload_generator_proto_msgTypes,
	}.Build()
	File_payload_generator_proto = out.File
	file_payload_generator_proto_goTypes = nil
	file_payload_generator_proto_depIdxs = nil
}
