//
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Representation of a tsunami plugin definition passed between language
// servers.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: plugin_representation.proto

package plugin_representation_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PluginInfo_PluginType int32

const (
	// Plugin is an unspecified type.
	PluginInfo_PLUGIN_TYPE_UNSPECIFIED PluginInfo_PluginType = 0
	// Plugin is a port scanner.
	PluginInfo_PORT_SCAN PluginInfo_PluginType = 1
	// Plugin is a service fingerprinter.
	PluginInfo_SERVICE_FINGERPRINT PluginInfo_PluginType = 2
	// Plugin is a vulnerability detector.
	PluginInfo_VULN_DETECTION PluginInfo_PluginType = 3
)

// Enum value maps for PluginInfo_PluginType.
var (
	PluginInfo_PluginType_name = map[int32]string{
		0: "PLUGIN_TYPE_UNSPECIFIED",
		1: "PORT_SCAN",
		2: "SERVICE_FINGERPRINT",
		3: "VULN_DETECTION",
	}
	PluginInfo_PluginType_value = map[string]int32{
		"PLUGIN_TYPE_UNSPECIFIED": 0,
		"PORT_SCAN":               1,
		"SERVICE_FINGERPRINT":     2,
		"VULN_DETECTION":          3,
	}
)

func (x PluginInfo_PluginType) Enum() *PluginInfo_PluginType {
	p := new(PluginInfo_PluginType)
	*p = x
	return p
}

func (x PluginInfo_PluginType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginInfo_PluginType) Descriptor() protoreflect.EnumDescriptor {
	return file_plugin_representation_proto_enumTypes[0].Descriptor()
}

func (PluginInfo_PluginType) Type() protoreflect.EnumType {
	return &file_plugin_representation_proto_enumTypes[0]
}

func (x PluginInfo_PluginType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Represents a PluginDefinition placeholder.
type PluginDefinition struct {
	state                                 protoimpl.MessageState      `protogen:"opaque.v1"`
	xxx_hidden_Info                       *PluginInfo                 `protobuf:"bytes,1,opt,name=info,proto3"`
	xxx_hidden_TargetServiceName          *TargetServiceName          `protobuf:"bytes,2,opt,name=target_service_name,json=targetServiceName,proto3"`
	xxx_hidden_TargetSoftware             *TargetSoftware             `protobuf:"bytes,3,opt,name=target_software,json=targetSoftware,proto3"`
	xxx_hidden_ForWebService              bool                        `protobuf:"varint,4,opt,name=for_web_service,json=forWebService,proto3"`
	xxx_hidden_TargetOperatingSystemClass *TargetOperatingSystemClass `protobuf:"bytes,5,opt,name=target_operating_system_class,json=targetOperatingSystemClass,proto3"`
	unknownFields                         protoimpl.UnknownFields
	sizeCache                             protoimpl.SizeCache
}

func (x *PluginDefinition) Reset() {
	*x = PluginDefinition{}
	mi := &file_plugin_representation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginDefinition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDefinition) ProtoMessage() {}

func (x *PluginDefinition) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_representation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginDefinition) GetInfo() *PluginInfo {
	if x != nil {
		return x.xxx_hidden_Info
	}
	return nil
}

func (x *PluginDefinition) GetTargetServiceName() *TargetServiceName {
	if x != nil {
		return x.xxx_hidden_TargetServiceName
	}
	return nil
}

func (x *PluginDefinition) GetTargetSoftware() *TargetSoftware {
	if x != nil {
		return x.xxx_hidden_TargetSoftware
	}
	return nil
}

func (x *PluginDefinition) GetForWebService() bool {
	if x != nil {
		return x.xxx_hidden_ForWebService
	}
	return false
}

func (x *PluginDefinition) GetTargetOperatingSystemClass() *TargetOperatingSystemClass {
	if x != nil {
		return x.xxx_hidden_TargetOperatingSystemClass
	}
	return nil
}

func (x *PluginDefinition) SetInfo(v *PluginInfo) {
	x.xxx_hidden_Info = v
}

func (x *PluginDefinition) SetTargetServiceName(v *TargetServiceName) {
	x.xxx_hidden_TargetServiceName = v
}

func (x *PluginDefinition) SetTargetSoftware(v *TargetSoftware) {
	x.xxx_hidden_TargetSoftware = v
}

func (x *PluginDefinition) SetForWebService(v bool) {
	x.xxx_hidden_ForWebService = v
}

func (x *PluginDefinition) SetTargetOperatingSystemClass(v *TargetOperatingSystemClass) {
	x.xxx_hidden_TargetOperatingSystemClass = v
}

func (x *PluginDefinition) HasInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Info != nil
}

func (x *PluginDefinition) HasTargetServiceName() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TargetServiceName != nil
}

func (x *PluginDefinition) HasTargetSoftware() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TargetSoftware != nil
}

func (x *PluginDefinition) HasTargetOperatingSystemClass() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TargetOperatingSystemClass != nil
}

func (x *PluginDefinition) ClearInfo() {
	x.xxx_hidden_Info = nil
}

func (x *PluginDefinition) ClearTargetServiceName() {
	x.xxx_hidden_TargetServiceName = nil
}

func (x *PluginDefinition) ClearTargetSoftware() {
	x.xxx_hidden_TargetSoftware = nil
}

func (x *PluginDefinition) ClearTargetOperatingSystemClass() {
	x.xxx_hidden_TargetOperatingSystemClass = nil
}

type PluginDefinition_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// PluginInfo of this definition.
	Info *PluginInfo
	// The name of the target service.
	TargetServiceName *TargetServiceName
	// The name of the target software.
	TargetSoftware *TargetSoftware
	// If the definition is for a web service or not.
	ForWebService bool
	// If the definition is for a specific operating system or not.
	// Note: this filter is executed within an AND condition with the other
	// filters. E.g. if target_service_name.value is "http" and
	// target_operating_system.osclass.family is "Linux" then the plugin will only
	// match if the service is http and the operating system is Linux.
	TargetOperatingSystemClass *TargetOperatingSystemClass
}

func (b0 PluginDefinition_builder) Build() *PluginDefinition {
	m0 := &PluginDefinition{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Info = b.Info
	x.xxx_hidden_TargetServiceName = b.TargetServiceName
	x.xxx_hidden_TargetSoftware = b.TargetSoftware
	x.xxx_hidden_ForWebService = b.ForWebService
	x.xxx_hidden_TargetOperatingSystemClass = b.TargetOperatingSystemClass
	return m0
}

// Represents a PluginInfo annotation placeholder used by the
// PluginDefinition proto above.
type PluginInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type        PluginInfo_PluginType  `protobuf:"varint,1,opt,name=type,proto3,enum=tsunami.proto.PluginInfo_PluginType"`
	xxx_hidden_Name        string                 `protobuf:"bytes,2,opt,name=name,proto3"`
	xxx_hidden_Version     string                 `protobuf:"bytes,3,opt,name=version,proto3"`
	xxx_hidden_Description string                 `protobuf:"bytes,4,opt,name=description,proto3"`
	xxx_hidden_Author      string                 `protobuf:"bytes,5,opt,name=author,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *PluginInfo) Reset() {
	*x = PluginInfo{}
	mi := &file_plugin_representation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInfo) ProtoMessage() {}

func (x *PluginInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_representation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PluginInfo) GetType() PluginInfo_PluginType {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return PluginInfo_PLUGIN_TYPE_UNSPECIFIED
}

func (x *PluginInfo) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *PluginInfo) GetVersion() string {
	if x != nil {
		return x.xxx_hidden_Version
	}
	return ""
}

func (x *PluginInfo) GetDescription() string {
	if x != nil {
		return x.xxx_hidden_Description
	}
	return ""
}

func (x *PluginInfo) GetAuthor() string {
	if x != nil {
		return x.xxx_hidden_Author
	}
	return ""
}

func (x *PluginInfo) SetType(v PluginInfo_PluginType) {
	x.xxx_hidden_Type = v
}

func (x *PluginInfo) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *PluginInfo) SetVersion(v string) {
	x.xxx_hidden_Version = v
}

func (x *PluginInfo) SetDescription(v string) {
	x.xxx_hidden_Description = v
}

func (x *PluginInfo) SetAuthor(v string) {
	x.xxx_hidden_Author = v
}

type PluginInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Type of plugin.
	Type PluginInfo_PluginType
	// Name of the plugin.
	Name string
	// Version of the plugin
	Version string
	// Description of the plugin.
	Description string
	// Author of the plugin.
	Author string
}

func (b0 PluginInfo_builder) Build() *PluginInfo {
	m0 := &PluginInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Version = b.Version
	x.xxx_hidden_Description = b.Description
	x.xxx_hidden_Author = b.Author
	return m0
}

// Represents a ForServiceName annotation placeholder used by the
// PluginDefinition proto above.
type TargetServiceName struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Value []string               `protobuf:"bytes,1,rep,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TargetServiceName) Reset() {
	*x = TargetServiceName{}
	mi := &file_plugin_representation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetServiceName) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetServiceName) ProtoMessage() {}

func (x *TargetServiceName) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_representation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TargetServiceName) GetValue() []string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *TargetServiceName) SetValue(v []string) {
	x.xxx_hidden_Value = v
}

type TargetServiceName_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The value of the name of the target.
	Value []string
}

func (b0 TargetServiceName_builder) Build() *TargetServiceName {
	m0 := &TargetServiceName{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Value = b.Value
	return m0
}

// Represents a ForSoftware annotation placeholder used by the
// PluginDefinition proto above.
type TargetSoftware struct {
	state            protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name  string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	xxx_hidden_Value []string               `protobuf:"bytes,2,rep,name=value,proto3"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TargetSoftware) Reset() {
	*x = TargetSoftware{}
	mi := &file_plugin_representation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetSoftware) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetSoftware) ProtoMessage() {}

func (x *TargetSoftware) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_representation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TargetSoftware) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *TargetSoftware) GetValue() []string {
	if x != nil {
		return x.xxx_hidden_Value
	}
	return nil
}

func (x *TargetSoftware) SetName(v string) {
	x.xxx_hidden_Name = v
}

func (x *TargetSoftware) SetValue(v []string) {
	x.xxx_hidden_Value = v
}

type TargetSoftware_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The name of the target software, case insensitive.
	Name string
	// Array of versions and version ranges of the target software.
	Value []string
}

func (b0 TargetSoftware_builder) Build() *TargetSoftware {
	m0 := &TargetSoftware{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	x.xxx_hidden_Value = b.Value
	return m0
}

// Represents a ForOperatingSystem annotation placeholder used by the
// PluginDefinition proto above. These values are coming directly from the
// port scanner's output (e.g. nmap).
type TargetOperatingSystemClass struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Vendor      []string               `protobuf:"bytes,1,rep,name=vendor,proto3"`
	xxx_hidden_OsFamily    []string               `protobuf:"bytes,2,rep,name=os_family,json=osFamily,proto3"`
	xxx_hidden_MinAccuracy uint32                 `protobuf:"varint,3,opt,name=min_accuracy,json=minAccuracy,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *TargetOperatingSystemClass) Reset() {
	*x = TargetOperatingSystemClass{}
	mi := &file_plugin_representation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetOperatingSystemClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetOperatingSystemClass) ProtoMessage() {}

func (x *TargetOperatingSystemClass) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_representation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TargetOperatingSystemClass) GetVendor() []string {
	if x != nil {
		return x.xxx_hidden_Vendor
	}
	return nil
}

func (x *TargetOperatingSystemClass) GetOsFamily() []string {
	if x != nil {
		return x.xxx_hidden_OsFamily
	}
	return nil
}

func (x *TargetOperatingSystemClass) GetMinAccuracy() uint32 {
	if x != nil {
		return x.xxx_hidden_MinAccuracy
	}
	return 0
}

func (x *TargetOperatingSystemClass) SetVendor(v []string) {
	x.xxx_hidden_Vendor = v
}

func (x *TargetOperatingSystemClass) SetOsFamily(v []string) {
	x.xxx_hidden_OsFamily = v
}

func (x *TargetOperatingSystemClass) SetMinAccuracy(v uint32) {
	x.xxx_hidden_MinAccuracy = v
}

type TargetOperatingSystemClass_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The vendor of the target operating system, e.g. "Microsoft"
	Vendor []string
	// The family of the target operating system, e.g. "Windows"
	OsFamily []string
	// The minimum accuracy of the target operating system, e.g. 90
	MinAccuracy uint32
}

func (b0 TargetOperatingSystemClass_builder) Build() *TargetOperatingSystemClass {
	m0 := &TargetOperatingSystemClass{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Vendor = b.Vendor
	x.xxx_hidden_OsFamily = b.OsFamily
	x.xxx_hidden_MinAccuracy = b.MinAccuracy
	return m0
}

var File_plugin_representation_proto protoreflect.FileDescriptor

const file_plugin_representation_proto_rawDesc = "" +
	"\n" +
	"\x1bplugin_representation.proto\x12\rtsunami.proto\"\xf1\x02\n" +
	"\x10PluginDefinition\x12-\n" +
	"\x04info\x18\x01 \x01(\v2\x19.tsunami.proto.PluginInfoR\x04info\x12P\n" +
	"\x13target_service_name\x18\x02 \x01(\v2 .tsunami.proto.TargetServiceNameR\x11targetServiceName\x12F\n" +
	"\x0ftarget_software\x18\x03 \x01(\v2\x1d.tsunami.proto.TargetSoftwareR\x0etargetSoftware\x12&\n" +
	"\x0ffor_web_service\x18\x04 \x01(\bR\rforWebService\x12l\n" +
	"\x1dtarget_operating_system_class\x18\x05 \x01(\v2).tsunami.proto.TargetOperatingSystemClassR\x1atargetOperatingSystemClass\"\x95\x02\n" +
	"\n" +
	"PluginInfo\x128\n" +
	"\x04type\x18\x01 \x01(\x0e2$.tsunami.proto.PluginInfo.PluginTypeR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x16\n" +
	"\x06author\x18\x05 \x01(\tR\x06author\"e\n" +
	"\n" +
	"PluginType\x12\x1b\n" +
	"\x17PLUGIN_TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tPORT_SCAN\x10\x01\x12\x17\n" +
	"\x13SERVICE_FINGERPRINT\x10\x02\x12\x12\n" +
	"\x0eVULN_DETECTION\x10\x03\")\n" +
	"\x11TargetServiceName\x12\x14\n" +
	"\x05value\x18\x01 \x03(\tR\x05value\":\n" +
	"\x0eTargetSoftware\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x03(\tR\x05value\"t\n" +
	"\x1aTargetOperatingSystemClass\x12\x16\n" +
	"\x06vendor\x18\x01 \x03(\tR\x06vendor\x12\x1b\n" +
	"\tos_family\x18\x02 \x03(\tR\bosFamily\x12!\n" +
	"\fmin_accuracy\x18\x03 \x01(\rR\vminAccuracyB\x8c\x01\n" +
	"\x18com.google.tsunami.protoB\x1aPluginRepresentationProtosP\x01ZRgithub.com/google/tsunami-security-scanner/proto/go/plugin_representation_go_protob\x06proto3"

var file_plugin_representation_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_plugin_representation_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_plugin_representation_proto_goTypes = []any{
	(PluginInfo_PluginType)(0),         // 0: tsunami.proto.PluginInfo.PluginType
	(*PluginDefinition)(nil),           // 1: tsunami.proto.PluginDefinition
	(*PluginInfo)(nil),                 // 2: tsunami.proto.PluginInfo
	(*TargetServiceName)(nil),          // 3: tsunami.proto.TargetServiceName
	(*TargetSoftware)(nil),             // 4: tsunami.proto.TargetSoftware
	(*TargetOperatingSystemClass)(nil), // 5: tsunami.proto.TargetOperatingSystemClass
}
var file_plugin_representation_proto_depIdxs = []int32{
	2, // 0: tsunami.proto.PluginDefinition.info:type_name -> tsunami.proto.PluginInfo
	3, // 1: tsunami.proto.PluginDefinition.target_service_name:type_name -> tsunami.proto.TargetServiceName
	4, // 2: tsunami.proto.PluginDefinition.target_software:type_name -> tsunami.proto.TargetSoftware
	5, // 3: tsunami.proto.PluginDefinition.target_operating_system_class:type_name -> tsunami.proto.TargetOperatingSystemClass
	0, // 4: tsunami.proto.PluginInfo.type:type_name -> tsunami.proto.PluginInfo.PluginType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_plugin_representation_proto_init() }
func file_plugin_representation_proto_init() {
	if File_plugin_representation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_representation_proto_rawDesc), len(file_plugin_representation_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_plugin_representation_proto_goTypes,
		DependencyIndexes: file_plugin_representation_proto_depIdxs,
		EnumInfos:         file_plugin_representation_proto_enumTypes,
		MessageInfos:      file_plugin_representation_proto_msgTypes,
	}.Build()
	File_plugin_representation_proto = out.File
	file_plugin_representation_proto_goTypes = nil
	file_plugin_representation_proto_depIdxs = nil
}
