//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Data models for describing a network service.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: network_service.proto

package network_service_go_proto

import (
	network_go_proto "github.com/google/tsunami-security-scanner/proto/go/network_go_proto"
	software_go_proto "github.com/google/tsunami-security-scanner/proto/go/software_go_proto"
	web_crawl_go_proto "github.com/google/tsunami-security-scanner/proto/go/web_crawl_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// General information about a network service running on a target.
type NetworkService struct {
	state                           protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_NetworkEndpoint      *network_go_proto.NetworkEndpoint  `protobuf:"bytes,1,opt,name=network_endpoint,json=networkEndpoint,proto3"`
	xxx_hidden_TransportProtocol    network_go_proto.TransportProtocol `protobuf:"varint,2,opt,name=transport_protocol,json=transportProtocol,proto3,enum=tsunami.proto.TransportProtocol"`
	xxx_hidden_ServiceName          string                             `protobuf:"bytes,3,opt,name=service_name,json=serviceName,proto3"`
	xxx_hidden_Software             *software_go_proto.Software        `protobuf:"bytes,4,opt,name=software,proto3"`
	xxx_hidden_VersionSet           *software_go_proto.VersionSet      `protobuf:"bytes,5,opt,name=version_set,json=versionSet,proto3"`
	xxx_hidden_Banner               []string                           `protobuf:"bytes,6,rep,name=banner,proto3"`
	xxx_hidden_ServiceContext       *ServiceContext                    `protobuf:"bytes,7,opt,name=service_context,json=serviceContext,proto3"`
	xxx_hidden_Cpes                 []string                           `protobuf:"bytes,8,rep,name=cpes,proto3"`
	xxx_hidden_SupportedSslVersions []string                           `protobuf:"bytes,9,rep,name=supported_ssl_versions,json=supportedSslVersions,proto3"`
	xxx_hidden_SupportedHttpMethods []string                           `protobuf:"bytes,10,rep,name=supported_http_methods,json=supportedHttpMethods,proto3"`
	unknownFields                   protoimpl.UnknownFields
	sizeCache                       protoimpl.SizeCache
}

func (x *NetworkService) Reset() {
	*x = NetworkService{}
	mi := &file_network_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkService) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkService) ProtoMessage() {}

func (x *NetworkService) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkService) GetNetworkEndpoint() *network_go_proto.NetworkEndpoint {
	if x != nil {
		return x.xxx_hidden_NetworkEndpoint
	}
	return nil
}

func (x *NetworkService) GetTransportProtocol() network_go_proto.TransportProtocol {
	if x != nil {
		return x.xxx_hidden_TransportProtocol
	}
	return network_go_proto.TransportProtocol(0)
}

func (x *NetworkService) GetServiceName() string {
	if x != nil {
		return x.xxx_hidden_ServiceName
	}
	return ""
}

func (x *NetworkService) GetSoftware() *software_go_proto.Software {
	if x != nil {
		return x.xxx_hidden_Software
	}
	return nil
}

func (x *NetworkService) GetVersionSet() *software_go_proto.VersionSet {
	if x != nil {
		return x.xxx_hidden_VersionSet
	}
	return nil
}

func (x *NetworkService) GetBanner() []string {
	if x != nil {
		return x.xxx_hidden_Banner
	}
	return nil
}

func (x *NetworkService) GetServiceContext() *ServiceContext {
	if x != nil {
		return x.xxx_hidden_ServiceContext
	}
	return nil
}

func (x *NetworkService) GetCpes() []string {
	if x != nil {
		return x.xxx_hidden_Cpes
	}
	return nil
}

func (x *NetworkService) GetSupportedSslVersions() []string {
	if x != nil {
		return x.xxx_hidden_SupportedSslVersions
	}
	return nil
}

func (x *NetworkService) GetSupportedHttpMethods() []string {
	if x != nil {
		return x.xxx_hidden_SupportedHttpMethods
	}
	return nil
}

func (x *NetworkService) SetNetworkEndpoint(v *network_go_proto.NetworkEndpoint) {
	x.xxx_hidden_NetworkEndpoint = v
}

func (x *NetworkService) SetTransportProtocol(v network_go_proto.TransportProtocol) {
	x.xxx_hidden_TransportProtocol = v
}

func (x *NetworkService) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = v
}

func (x *NetworkService) SetSoftware(v *software_go_proto.Software) {
	x.xxx_hidden_Software = v
}

func (x *NetworkService) SetVersionSet(v *software_go_proto.VersionSet) {
	x.xxx_hidden_VersionSet = v
}

func (x *NetworkService) SetBanner(v []string) {
	x.xxx_hidden_Banner = v
}

func (x *NetworkService) SetServiceContext(v *ServiceContext) {
	x.xxx_hidden_ServiceContext = v
}

func (x *NetworkService) SetCpes(v []string) {
	x.xxx_hidden_Cpes = v
}

func (x *NetworkService) SetSupportedSslVersions(v []string) {
	x.xxx_hidden_SupportedSslVersions = v
}

func (x *NetworkService) SetSupportedHttpMethods(v []string) {
	x.xxx_hidden_SupportedHttpMethods = v
}

func (x *NetworkService) HasNetworkEndpoint() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_NetworkEndpoint != nil
}

func (x *NetworkService) HasSoftware() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Software != nil
}

func (x *NetworkService) HasVersionSet() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_VersionSet != nil
}

func (x *NetworkService) HasServiceContext() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ServiceContext != nil
}

func (x *NetworkService) ClearNetworkEndpoint() {
	x.xxx_hidden_NetworkEndpoint = nil
}

func (x *NetworkService) ClearSoftware() {
	x.xxx_hidden_Software = nil
}

func (x *NetworkService) ClearVersionSet() {
	x.xxx_hidden_VersionSet = nil
}

func (x *NetworkService) ClearServiceContext() {
	x.xxx_hidden_ServiceContext = nil
}

type NetworkService_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The network endpoint where this network service is served.
	NetworkEndpoint *network_go_proto.NetworkEndpoint
	// The transport layer protocol used by the service.
	TransportProtocol network_go_proto.TransportProtocol
	// The name of the network service, following convention in RFC6335. Examples
	// are like http, telnet, ssh, etc.
	ServiceName string
	// The software that provides the service behind the port.
	Software *software_go_proto.Software
	// The complete set of versions of the software.
	VersionSet *software_go_proto.VersionSet
	// Banners generated by the service.
	Banner []string
	// Context information about this network service.
	ServiceContext *ServiceContext
	// The detected Common Platform Enumeration (CPE) name for service,
	// in the uri binding representation, like: cpe:/a:openbsd:openssh:8.4p1
	Cpes []string
	// List of supported SSL versions (e.g. TLSv1, SSLv3, ...) on the service.
	SupportedSslVersions []string
	// List of supported HTTP methods (e.g. POST, GET, ...) on the service.
	SupportedHttpMethods []string
}

func (b0 NetworkService_builder) Build() *NetworkService {
	m0 := &NetworkService{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NetworkEndpoint = b.NetworkEndpoint
	x.xxx_hidden_TransportProtocol = b.TransportProtocol
	x.xxx_hidden_ServiceName = b.ServiceName
	x.xxx_hidden_Software = b.Software
	x.xxx_hidden_VersionSet = b.VersionSet
	x.xxx_hidden_Banner = b.Banner
	x.xxx_hidden_ServiceContext = b.ServiceContext
	x.xxx_hidden_Cpes = b.Cpes
	x.xxx_hidden_SupportedSslVersions = b.SupportedSslVersions
	x.xxx_hidden_SupportedHttpMethods = b.SupportedHttpMethods
	return m0
}

// Context information about a specific network service.
type ServiceContext struct {
	state              protoimpl.MessageState   `protogen:"opaque.v1"`
	xxx_hidden_Context isServiceContext_Context `protobuf_oneof:"context"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ServiceContext) Reset() {
	*x = ServiceContext{}
	mi := &file_network_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceContext) ProtoMessage() {}

func (x *ServiceContext) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ServiceContext) GetWebServiceContext() *WebServiceContext {
	if x != nil {
		if x, ok := x.xxx_hidden_Context.(*serviceContext_WebServiceContext); ok {
			return x.WebServiceContext
		}
	}
	return nil
}

func (x *ServiceContext) SetWebServiceContext(v *WebServiceContext) {
	if v == nil {
		x.xxx_hidden_Context = nil
		return
	}
	x.xxx_hidden_Context = &serviceContext_WebServiceContext{v}
}

func (x *ServiceContext) HasContext() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Context != nil
}

func (x *ServiceContext) HasWebServiceContext() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Context.(*serviceContext_WebServiceContext)
	return ok
}

func (x *ServiceContext) ClearContext() {
	x.xxx_hidden_Context = nil
}

func (x *ServiceContext) ClearWebServiceContext() {
	if _, ok := x.xxx_hidden_Context.(*serviceContext_WebServiceContext); ok {
		x.xxx_hidden_Context = nil
	}
}

const ServiceContext_Context_not_set_case case_ServiceContext_Context = 0
const ServiceContext_WebServiceContext_case case_ServiceContext_Context = 1

func (x *ServiceContext) WhichContext() case_ServiceContext_Context {
	if x == nil {
		return ServiceContext_Context_not_set_case
	}
	switch x.xxx_hidden_Context.(type) {
	case *serviceContext_WebServiceContext:
		return ServiceContext_WebServiceContext_case
	default:
		return ServiceContext_Context_not_set_case
	}
}

type ServiceContext_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Context:
	WebServiceContext *WebServiceContext
	// -- end of xxx_hidden_Context
}

func (b0 ServiceContext_builder) Build() *ServiceContext {
	m0 := &ServiceContext{}
	b, x := &b0, m0
	_, _ = b, x
	if b.WebServiceContext != nil {
		x.xxx_hidden_Context = &serviceContext_WebServiceContext{b.WebServiceContext}
	}
	return m0
}

type case_ServiceContext_Context protoreflect.FieldNumber

func (x case_ServiceContext_Context) String() string {
	md := file_network_service_proto_msgTypes[1].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isServiceContext_Context interface {
	isServiceContext_Context()
}

type serviceContext_WebServiceContext struct {
	WebServiceContext *WebServiceContext `protobuf:"bytes,1,opt,name=web_service_context,json=webServiceContext,proto3,oneof"`
}

func (*serviceContext_WebServiceContext) isServiceContext_Context() {}

// Context information about a web application.
// NEXT ID: 5
type WebServiceContext struct {
	state                      protoimpl.MessageState             `protogen:"opaque.v1"`
	xxx_hidden_ApplicationRoot string                             `protobuf:"bytes,1,opt,name=application_root,json=applicationRoot,proto3"`
	xxx_hidden_Software        *software_go_proto.Software        `protobuf:"bytes,2,opt,name=software,proto3"`
	xxx_hidden_VersionSet      *software_go_proto.VersionSet      `protobuf:"bytes,3,opt,name=version_set,json=versionSet,proto3"`
	xxx_hidden_CrawlResults    *[]*web_crawl_go_proto.CrawlResult `protobuf:"bytes,4,rep,name=crawl_results,json=crawlResults,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *WebServiceContext) Reset() {
	*x = WebServiceContext{}
	mi := &file_network_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebServiceContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebServiceContext) ProtoMessage() {}

func (x *WebServiceContext) ProtoReflect() protoreflect.Message {
	mi := &file_network_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *WebServiceContext) GetApplicationRoot() string {
	if x != nil {
		return x.xxx_hidden_ApplicationRoot
	}
	return ""
}

func (x *WebServiceContext) GetSoftware() *software_go_proto.Software {
	if x != nil {
		return x.xxx_hidden_Software
	}
	return nil
}

func (x *WebServiceContext) GetVersionSet() *software_go_proto.VersionSet {
	if x != nil {
		return x.xxx_hidden_VersionSet
	}
	return nil
}

func (x *WebServiceContext) GetCrawlResults() []*web_crawl_go_proto.CrawlResult {
	if x != nil {
		if x.xxx_hidden_CrawlResults != nil {
			return *x.xxx_hidden_CrawlResults
		}
	}
	return nil
}

func (x *WebServiceContext) SetApplicationRoot(v string) {
	x.xxx_hidden_ApplicationRoot = v
}

func (x *WebServiceContext) SetSoftware(v *software_go_proto.Software) {
	x.xxx_hidden_Software = v
}

func (x *WebServiceContext) SetVersionSet(v *software_go_proto.VersionSet) {
	x.xxx_hidden_VersionSet = v
}

func (x *WebServiceContext) SetCrawlResults(v []*web_crawl_go_proto.CrawlResult) {
	x.xxx_hidden_CrawlResults = &v
}

func (x *WebServiceContext) HasSoftware() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Software != nil
}

func (x *WebServiceContext) HasVersionSet() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_VersionSet != nil
}

func (x *WebServiceContext) ClearSoftware() {
	x.xxx_hidden_Software = nil
}

func (x *WebServiceContext) ClearVersionSet() {
	x.xxx_hidden_VersionSet = nil
}

type WebServiceContext_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The root path of the hosted web application.
	ApplicationRoot string
	// The web application that is serving under the application root.
	Software *software_go_proto.Software
	// The detected versions of the web application.
	VersionSet *software_go_proto.VersionSet
	// Fingerprinter's crawling results for this web service.
	CrawlResults []*web_crawl_go_proto.CrawlResult
}

func (b0 WebServiceContext_builder) Build() *WebServiceContext {
	m0 := &WebServiceContext{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_ApplicationRoot = b.ApplicationRoot
	x.xxx_hidden_Software = b.Software
	x.xxx_hidden_VersionSet = b.VersionSet
	x.xxx_hidden_CrawlResults = &b.CrawlResults
	return m0
}

var File_network_service_proto protoreflect.FileDescriptor

const file_network_service_proto_rawDesc = "" +
	"\n" +
	"\x15network_service.proto\x12\rtsunami.proto\x1a\rnetwork.proto\x1a\x0esoftware.proto\x1a\x0fweb_crawl.proto\"\xa0\x04\n" +
	"\x0eNetworkService\x12I\n" +
	"\x10network_endpoint\x18\x01 \x01(\v2\x1e.tsunami.proto.NetworkEndpointR\x0fnetworkEndpoint\x12O\n" +
	"\x12transport_protocol\x18\x02 \x01(\x0e2 .tsunami.proto.TransportProtocolR\x11transportProtocol\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x123\n" +
	"\bsoftware\x18\x04 \x01(\v2\x17.tsunami.proto.SoftwareR\bsoftware\x12:\n" +
	"\vversion_set\x18\x05 \x01(\v2\x19.tsunami.proto.VersionSetR\n" +
	"versionSet\x12\x16\n" +
	"\x06banner\x18\x06 \x03(\tR\x06banner\x12F\n" +
	"\x0fservice_context\x18\a \x01(\v2\x1d.tsunami.proto.ServiceContextR\x0eserviceContext\x12\x12\n" +
	"\x04cpes\x18\b \x03(\tR\x04cpes\x124\n" +
	"\x16supported_ssl_versions\x18\t \x03(\tR\x14supportedSslVersions\x124\n" +
	"\x16supported_http_methods\x18\n" +
	" \x03(\tR\x14supportedHttpMethods\"o\n" +
	"\x0eServiceContext\x12R\n" +
	"\x13web_service_context\x18\x01 \x01(\v2 .tsunami.proto.WebServiceContextH\x00R\x11webServiceContextB\t\n" +
	"\acontext\"\xf0\x01\n" +
	"\x11WebServiceContext\x12)\n" +
	"\x10application_root\x18\x01 \x01(\tR\x0fapplicationRoot\x123\n" +
	"\bsoftware\x18\x02 \x01(\v2\x17.tsunami.proto.SoftwareR\bsoftware\x12:\n" +
	"\vversion_set\x18\x03 \x01(\v2\x19.tsunami.proto.VersionSetR\n" +
	"versionSet\x12?\n" +
	"\rcrawl_results\x18\x04 \x03(\v2\x1a.tsunami.proto.CrawlResultR\fcrawlResultsB\x80\x01\n" +
	"\x18com.google.tsunami.protoB\x14NetworkServiceProtosP\x01ZLgithub.com/google/tsunami-security-scanner/proto/go/network_service_go_protob\x06proto3"

var file_network_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_network_service_proto_goTypes = []any{
	(*NetworkService)(nil),                   // 0: tsunami.proto.NetworkService
	(*ServiceContext)(nil),                   // 1: tsunami.proto.ServiceContext
	(*WebServiceContext)(nil),                // 2: tsunami.proto.WebServiceContext
	(*network_go_proto.NetworkEndpoint)(nil), // 3: tsunami.proto.NetworkEndpoint
	(network_go_proto.TransportProtocol)(0),  // 4: tsunami.proto.TransportProtocol
	(*software_go_proto.Software)(nil),       // 5: tsunami.proto.Software
	(*software_go_proto.VersionSet)(nil),     // 6: tsunami.proto.VersionSet
	(*web_crawl_go_proto.CrawlResult)(nil),   // 7: tsunami.proto.CrawlResult
}
var file_network_service_proto_depIdxs = []int32{
	3, // 0: tsunami.proto.NetworkService.network_endpoint:type_name -> tsunami.proto.NetworkEndpoint
	4, // 1: tsunami.proto.NetworkService.transport_protocol:type_name -> tsunami.proto.TransportProtocol
	5, // 2: tsunami.proto.NetworkService.software:type_name -> tsunami.proto.Software
	6, // 3: tsunami.proto.NetworkService.version_set:type_name -> tsunami.proto.VersionSet
	1, // 4: tsunami.proto.NetworkService.service_context:type_name -> tsunami.proto.ServiceContext
	2, // 5: tsunami.proto.ServiceContext.web_service_context:type_name -> tsunami.proto.WebServiceContext
	5, // 6: tsunami.proto.WebServiceContext.software:type_name -> tsunami.proto.Software
	6, // 7: tsunami.proto.WebServiceContext.version_set:type_name -> tsunami.proto.VersionSet
	7, // 8: tsunami.proto.WebServiceContext.crawl_results:type_name -> tsunami.proto.CrawlResult
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_network_service_proto_init() }
func file_network_service_proto_init() {
	if File_network_service_proto != nil {
		return
	}
	file_network_service_proto_msgTypes[1].OneofWrappers = []any{
		(*serviceContext_WebServiceContext)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_service_proto_rawDesc), len(file_network_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_service_proto_goTypes,
		DependencyIndexes: file_network_service_proto_depIdxs,
		MessageInfos:      file_network_service_proto_msgTypes,
	}.Build()
	File_network_service_proto = out.File
	file_network_service_proto_goTypes = nil
	file_network_service_proto_depIdxs = nil
}
