//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Data models for describing network related information.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: network.proto

package network_go_proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The address family of an IP address.
type AddressFamily int32

const (
	AddressFamily_ADDRESS_FAMILY_UNSPECIFIED AddressFamily = 0
	AddressFamily_IPV4                       AddressFamily = 4
	AddressFamily_IPV6                       AddressFamily = 6
)

// Enum value maps for AddressFamily.
var (
	AddressFamily_name = map[int32]string{
		0: "ADDRESS_FAMILY_UNSPECIFIED",
		4: "IPV4",
		6: "IPV6",
	}
	AddressFamily_value = map[string]int32{
		"ADDRESS_FAMILY_UNSPECIFIED": 0,
		"IPV4":                       4,
		"IPV6":                       6,
	}
)

func (x AddressFamily) Enum() *AddressFamily {
	p := new(AddressFamily)
	*p = x
	return p
}

func (x AddressFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AddressFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[0].Descriptor()
}

func (AddressFamily) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[0]
}

func (x AddressFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The transport layer protocols.
type TransportProtocol int32

const (
	TransportProtocol_TRANSPORT_PROTOCOL_UNSPECIFIED TransportProtocol = 0
	TransportProtocol_TCP                            TransportProtocol = 1
	TransportProtocol_UDP                            TransportProtocol = 2
	TransportProtocol_SCTP                           TransportProtocol = 3
)

// Enum value maps for TransportProtocol.
var (
	TransportProtocol_name = map[int32]string{
		0: "TRANSPORT_PROTOCOL_UNSPECIFIED",
		1: "TCP",
		2: "UDP",
		3: "SCTP",
	}
	TransportProtocol_value = map[string]int32{
		"TRANSPORT_PROTOCOL_UNSPECIFIED": 0,
		"TCP":                            1,
		"UDP":                            2,
		"SCTP":                           3,
	}
)

func (x TransportProtocol) Enum() *TransportProtocol {
	p := new(TransportProtocol)
	*p = x
	return p
}

func (x TransportProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransportProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[1].Descriptor()
}

func (TransportProtocol) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[1]
}

func (x TransportProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type NetworkEndpoint_Type int32

const (
	NetworkEndpoint_TYPE_UNSPECIFIED NetworkEndpoint_Type = 0
	// The network endpoint is represented by an IP address.
	NetworkEndpoint_IP NetworkEndpoint_Type = 1
	// The network endpoint is represented by IP address and port pair.
	NetworkEndpoint_IP_PORT NetworkEndpoint_Type = 2
	// The network endpoint is represented by a hostname.
	NetworkEndpoint_HOSTNAME NetworkEndpoint_Type = 3
	// The network endpoint is represented by a hostname and port pair.
	NetworkEndpoint_HOSTNAME_PORT NetworkEndpoint_Type = 4
	// The network endpoint is represented by an IP address and hostname.
	NetworkEndpoint_IP_HOSTNAME NetworkEndpoint_Type = 5
	// The network endpoint is represented by an IP address, hostname and port.
	NetworkEndpoint_IP_HOSTNAME_PORT NetworkEndpoint_Type = 6
)

// Enum value maps for NetworkEndpoint_Type.
var (
	NetworkEndpoint_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "IP",
		2: "IP_PORT",
		3: "HOSTNAME",
		4: "HOSTNAME_PORT",
		5: "IP_HOSTNAME",
		6: "IP_HOSTNAME_PORT",
	}
	NetworkEndpoint_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"IP":               1,
		"IP_PORT":          2,
		"HOSTNAME":         3,
		"HOSTNAME_PORT":    4,
		"IP_HOSTNAME":      5,
		"IP_HOSTNAME_PORT": 6,
	}
)

func (x NetworkEndpoint_Type) Enum() *NetworkEndpoint_Type {
	p := new(NetworkEndpoint_Type)
	*p = x
	return p
}

func (x NetworkEndpoint_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NetworkEndpoint_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_network_proto_enumTypes[2].Descriptor()
}

func (NetworkEndpoint_Type) Type() protoreflect.EnumType {
	return &file_network_proto_enumTypes[2]
}

func (x NetworkEndpoint_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// The IP address of a networking device.
type IpAddress struct {
	state                    protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_AddressFamily AddressFamily          `protobuf:"varint,1,opt,name=address_family,json=addressFamily,proto3,enum=tsunami.proto.AddressFamily"`
	xxx_hidden_Address       string                 `protobuf:"bytes,2,opt,name=address,proto3"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *IpAddress) Reset() {
	*x = IpAddress{}
	mi := &file_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IpAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IpAddress) ProtoMessage() {}

func (x *IpAddress) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *IpAddress) GetAddressFamily() AddressFamily {
	if x != nil {
		return x.xxx_hidden_AddressFamily
	}
	return AddressFamily_ADDRESS_FAMILY_UNSPECIFIED
}

func (x *IpAddress) GetAddress() string {
	if x != nil {
		return x.xxx_hidden_Address
	}
	return ""
}

func (x *IpAddress) SetAddressFamily(v AddressFamily) {
	x.xxx_hidden_AddressFamily = v
}

func (x *IpAddress) SetAddress(v string) {
	x.xxx_hidden_Address = v
}

type IpAddress_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The family of the IP address.
	AddressFamily AddressFamily
	// A human-readable representation of the IP address, e.g. 127.0.0.1 for IPV4
	// and 2001:db8:0:1234:0:567:8:1 for IPV6.
	Address string
}

func (b0 IpAddress_builder) Build() *IpAddress {
	m0 := &IpAddress{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_AddressFamily = b.AddressFamily
	x.xxx_hidden_Address = b.Address
	return m0
}

// The port that a network service listens to.
type Port struct {
	state                 protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PortNumber uint32                 `protobuf:"varint,1,opt,name=port_number,json=portNumber,proto3"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Port) Reset() {
	*x = Port{}
	mi := &file_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Port) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Port) ProtoMessage() {}

func (x *Port) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Port) GetPortNumber() uint32 {
	if x != nil {
		return x.xxx_hidden_PortNumber
	}
	return 0
}

func (x *Port) SetPortNumber(v uint32) {
	x.xxx_hidden_PortNumber = v
}

type Port_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	PortNumber uint32
}

func (b0 Port_builder) Build() *Port {
	m0 := &Port{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PortNumber = b.PortNumber
	return m0
}

// The hostname of a networking device.
type Hostname struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Name string                 `protobuf:"bytes,1,opt,name=name,proto3"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hostname) Reset() {
	*x = Hostname{}
	mi := &file_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hostname) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hostname) ProtoMessage() {}

func (x *Hostname) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Hostname) GetName() string {
	if x != nil {
		return x.xxx_hidden_Name
	}
	return ""
}

func (x *Hostname) SetName(v string) {
	x.xxx_hidden_Name = v
}

type Hostname_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Name string
}

func (b0 Hostname_builder) Build() *Hostname {
	m0 := &Hostname{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Name = b.Name
	return m0
}

// A classification of an endpoint for a network device.
type NetworkEndpoint struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type      NetworkEndpoint_Type   `protobuf:"varint,1,opt,name=type,proto3,enum=tsunami.proto.NetworkEndpoint_Type"`
	xxx_hidden_IpAddress *IpAddress             `protobuf:"bytes,2,opt,name=ip_address,json=ipAddress,proto3"`
	xxx_hidden_Port      *Port                  `protobuf:"bytes,3,opt,name=port,proto3"`
	xxx_hidden_Hostname  *Hostname              `protobuf:"bytes,4,opt,name=hostname,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *NetworkEndpoint) Reset() {
	*x = NetworkEndpoint{}
	mi := &file_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NetworkEndpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkEndpoint) ProtoMessage() {}

func (x *NetworkEndpoint) ProtoReflect() protoreflect.Message {
	mi := &file_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *NetworkEndpoint) GetType() NetworkEndpoint_Type {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return NetworkEndpoint_TYPE_UNSPECIFIED
}

func (x *NetworkEndpoint) GetIpAddress() *IpAddress {
	if x != nil {
		return x.xxx_hidden_IpAddress
	}
	return nil
}

func (x *NetworkEndpoint) GetPort() *Port {
	if x != nil {
		return x.xxx_hidden_Port
	}
	return nil
}

func (x *NetworkEndpoint) GetHostname() *Hostname {
	if x != nil {
		return x.xxx_hidden_Hostname
	}
	return nil
}

func (x *NetworkEndpoint) SetType(v NetworkEndpoint_Type) {
	x.xxx_hidden_Type = v
}

func (x *NetworkEndpoint) SetIpAddress(v *IpAddress) {
	x.xxx_hidden_IpAddress = v
}

func (x *NetworkEndpoint) SetPort(v *Port) {
	x.xxx_hidden_Port = v
}

func (x *NetworkEndpoint) SetHostname(v *Hostname) {
	x.xxx_hidden_Hostname = v
}

func (x *NetworkEndpoint) HasIpAddress() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_IpAddress != nil
}

func (x *NetworkEndpoint) HasPort() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Port != nil
}

func (x *NetworkEndpoint) HasHostname() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Hostname != nil
}

func (x *NetworkEndpoint) ClearIpAddress() {
	x.xxx_hidden_IpAddress = nil
}

func (x *NetworkEndpoint) ClearPort() {
	x.xxx_hidden_Port = nil
}

func (x *NetworkEndpoint) ClearHostname() {
	x.xxx_hidden_Hostname = nil
}

type NetworkEndpoint_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Type of the network endpoint.
	Type NetworkEndpoint_Type
	// Optional IP address of a network endpoint. Must be specified when Type is
	// IP or IP_PORT.
	IpAddress *IpAddress
	// Optional port of a network endpoint. Must be specified when Type is IP_PORT
	// or HOSTNAME_PORT.
	Port *Port
	// Optional hostname of a network endpoint. Must be specified when Type is
	// HOSTNAME or HOSTNAME_PORT.
	Hostname *Hostname
}

func (b0 NetworkEndpoint_builder) Build() *NetworkEndpoint {
	m0 := &NetworkEndpoint{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_IpAddress = b.IpAddress
	x.xxx_hidden_Port = b.Port
	x.xxx_hidden_Hostname = b.Hostname
	return m0
}

var File_network_proto protoreflect.FileDescriptor

const file_network_proto_rawDesc = "" +
	"\n" +
	"\rnetwork.proto\x12\rtsunami.proto\"j\n" +
	"\tIpAddress\x12C\n" +
	"\x0eaddress_family\x18\x01 \x01(\x0e2\x1c.tsunami.proto.AddressFamilyR\raddressFamily\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\"'\n" +
	"\x04Port\x12\x1f\n" +
	"\vport_number\x18\x01 \x01(\rR\n" +
	"portNumber\"\x1e\n" +
	"\bHostname\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\xdc\x02\n" +
	"\x0fNetworkEndpoint\x127\n" +
	"\x04type\x18\x01 \x01(\x0e2#.tsunami.proto.NetworkEndpoint.TypeR\x04type\x127\n" +
	"\n" +
	"ip_address\x18\x02 \x01(\v2\x18.tsunami.proto.IpAddressR\tipAddress\x12'\n" +
	"\x04port\x18\x03 \x01(\v2\x13.tsunami.proto.PortR\x04port\x123\n" +
	"\bhostname\x18\x04 \x01(\v2\x17.tsunami.proto.HostnameR\bhostname\"y\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\x06\n" +
	"\x02IP\x10\x01\x12\v\n" +
	"\aIP_PORT\x10\x02\x12\f\n" +
	"\bHOSTNAME\x10\x03\x12\x11\n" +
	"\rHOSTNAME_PORT\x10\x04\x12\x0f\n" +
	"\vIP_HOSTNAME\x10\x05\x12\x14\n" +
	"\x10IP_HOSTNAME_PORT\x10\x06*C\n" +
	"\rAddressFamily\x12\x1e\n" +
	"\x1aADDRESS_FAMILY_UNSPECIFIED\x10\x00\x12\b\n" +
	"\x04IPV4\x10\x04\x12\b\n" +
	"\x04IPV6\x10\x06*S\n" +
	"\x11TransportProtocol\x12\"\n" +
	"\x1eTRANSPORT_PROTOCOL_UNSPECIFIED\x10\x00\x12\a\n" +
	"\x03TCP\x10\x01\x12\a\n" +
	"\x03UDP\x10\x02\x12\b\n" +
	"\x04SCTP\x10\x03Bq\n" +
	"\x18com.google.tsunami.protoB\rNetworkProtosP\x01ZDgithub.com/google/tsunami-security-scanner/proto/go/network_go_protob\x06proto3"

var file_network_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_network_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_network_proto_goTypes = []any{
	(AddressFamily)(0),        // 0: tsunami.proto.AddressFamily
	(TransportProtocol)(0),    // 1: tsunami.proto.TransportProtocol
	(NetworkEndpoint_Type)(0), // 2: tsunami.proto.NetworkEndpoint.Type
	(*IpAddress)(nil),         // 3: tsunami.proto.IpAddress
	(*Port)(nil),              // 4: tsunami.proto.Port
	(*Hostname)(nil),          // 5: tsunami.proto.Hostname
	(*NetworkEndpoint)(nil),   // 6: tsunami.proto.NetworkEndpoint
}
var file_network_proto_depIdxs = []int32{
	0, // 0: tsunami.proto.IpAddress.address_family:type_name -> tsunami.proto.AddressFamily
	2, // 1: tsunami.proto.NetworkEndpoint.type:type_name -> tsunami.proto.NetworkEndpoint.Type
	3, // 2: tsunami.proto.NetworkEndpoint.ip_address:type_name -> tsunami.proto.IpAddress
	4, // 3: tsunami.proto.NetworkEndpoint.port:type_name -> tsunami.proto.Port
	5, // 4: tsunami.proto.NetworkEndpoint.hostname:type_name -> tsunami.proto.Hostname
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_network_proto_init() }
func file_network_proto_init() {
	if File_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_proto_rawDesc), len(file_network_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_network_proto_goTypes,
		DependencyIndexes: file_network_proto_depIdxs,
		EnumInfos:         file_network_proto_enumTypes,
		MessageInfos:      file_network_proto_msgTypes,
	}.Build()
	File_network_proto = out.File
	file_network_proto_goTypes = nil
	file_network_proto_depIdxs = nil
}
