//
// Copyright 2022 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Model for the plugin RPC service protocol.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: plugin_service.proto

package plugin_service_go_proto

import (
	detection_go_proto "github.com/google/tsunami-security-scanner/proto/go/detection_go_proto"
	network_service_go_proto "github.com/google/tsunami-security-scanner/proto/go/network_service_go_proto"
	plugin_representation_go_proto "github.com/google/tsunami-security-scanner/proto/go/plugin_representation_go_proto"
	reconnaissance_go_proto "github.com/google/tsunami-security-scanner/proto/go/reconnaissance_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Represents a run request with all matched plugins that will need to run
// as well as the target to run against.
type RunRequest struct {
	state              protoimpl.MessageState              `protogen:"opaque.v1"`
	xxx_hidden_Target  *reconnaissance_go_proto.TargetInfo `protobuf:"bytes,1,opt,name=target,proto3"`
	xxx_hidden_Plugins *[]*MatchedPlugin                   `protobuf:"bytes,2,rep,name=plugins,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunRequest) Reset() {
	*x = RunRequest{}
	mi := &file_plugin_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunRequest) ProtoMessage() {}

func (x *RunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RunRequest) GetTarget() *reconnaissance_go_proto.TargetInfo {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *RunRequest) GetPlugins() []*MatchedPlugin {
	if x != nil {
		if x.xxx_hidden_Plugins != nil {
			return *x.xxx_hidden_Plugins
		}
	}
	return nil
}

func (x *RunRequest) SetTarget(v *reconnaissance_go_proto.TargetInfo) {
	x.xxx_hidden_Target = v
}

func (x *RunRequest) SetPlugins(v []*MatchedPlugin) {
	x.xxx_hidden_Plugins = &v
}

func (x *RunRequest) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *RunRequest) ClearTarget() {
	x.xxx_hidden_Target = nil
}

type RunRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Target of the plugins.
	Target *reconnaissance_go_proto.TargetInfo
	// All matched plugins that will need to run.
	Plugins []*MatchedPlugin
}

func (b0 RunRequest_builder) Build() *RunRequest {
	m0 := &RunRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_Plugins = &b.Plugins
	return m0
}

// Compact representation of RunRequest.
type RunCompactRequest struct {
	state                  protoimpl.MessageState                              `protogen:"opaque.v1"`
	xxx_hidden_Target      *reconnaissance_go_proto.TargetInfo                 `protobuf:"bytes,1,opt,name=target,proto3"`
	xxx_hidden_Services    *[]*network_service_go_proto.NetworkService         `protobuf:"bytes,2,rep,name=services,proto3"`
	xxx_hidden_Plugins     *[]*plugin_representation_go_proto.PluginDefinition `protobuf:"bytes,3,rep,name=plugins,proto3"`
	xxx_hidden_ScanTargets *[]*RunCompactRequest_PluginNetworkServiceTarget    `protobuf:"bytes,4,rep,name=scan_targets,json=scanTargets,proto3"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RunCompactRequest) Reset() {
	*x = RunCompactRequest{}
	mi := &file_plugin_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCompactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCompactRequest) ProtoMessage() {}

func (x *RunCompactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RunCompactRequest) GetTarget() *reconnaissance_go_proto.TargetInfo {
	if x != nil {
		return x.xxx_hidden_Target
	}
	return nil
}

func (x *RunCompactRequest) GetServices() []*network_service_go_proto.NetworkService {
	if x != nil {
		if x.xxx_hidden_Services != nil {
			return *x.xxx_hidden_Services
		}
	}
	return nil
}

func (x *RunCompactRequest) GetPlugins() []*plugin_representation_go_proto.PluginDefinition {
	if x != nil {
		if x.xxx_hidden_Plugins != nil {
			return *x.xxx_hidden_Plugins
		}
	}
	return nil
}

func (x *RunCompactRequest) GetScanTargets() []*RunCompactRequest_PluginNetworkServiceTarget {
	if x != nil {
		if x.xxx_hidden_ScanTargets != nil {
			return *x.xxx_hidden_ScanTargets
		}
	}
	return nil
}

func (x *RunCompactRequest) SetTarget(v *reconnaissance_go_proto.TargetInfo) {
	x.xxx_hidden_Target = v
}

func (x *RunCompactRequest) SetServices(v []*network_service_go_proto.NetworkService) {
	x.xxx_hidden_Services = &v
}

func (x *RunCompactRequest) SetPlugins(v []*plugin_representation_go_proto.PluginDefinition) {
	x.xxx_hidden_Plugins = &v
}

func (x *RunCompactRequest) SetScanTargets(v []*RunCompactRequest_PluginNetworkServiceTarget) {
	x.xxx_hidden_ScanTargets = &v
}

func (x *RunCompactRequest) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *RunCompactRequest) ClearTarget() {
	x.xxx_hidden_Target = nil
}

type RunCompactRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Target of the plugins.
	Target *reconnaissance_go_proto.TargetInfo
	// All network services that are targeted by some of the plugins.
	Services []*network_service_go_proto.NetworkService
	// All plugins that should be executed during the run.
	Plugins []*plugin_representation_go_proto.PluginDefinition
	// The concrete map of plugin/network service pairs that should be scanned.
	ScanTargets []*RunCompactRequest_PluginNetworkServiceTarget
}

func (b0 RunCompactRequest_builder) Build() *RunCompactRequest {
	m0 := &RunCompactRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Target = b.Target
	x.xxx_hidden_Services = &b.Services
	x.xxx_hidden_Plugins = &b.Plugins
	x.xxx_hidden_ScanTargets = &b.ScanTargets
	return m0
}

// Represents the plugin needed to run by the language-specific server
// as well as all the matched network services for the plugin.
type MatchedPlugin struct {
	state               protoimpl.MessageState                           `protogen:"opaque.v1"`
	xxx_hidden_Services *[]*network_service_go_proto.NetworkService      `protobuf:"bytes,1,rep,name=services,proto3"`
	xxx_hidden_Plugin   *plugin_representation_go_proto.PluginDefinition `protobuf:"bytes,2,opt,name=plugin,proto3"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MatchedPlugin) Reset() {
	*x = MatchedPlugin{}
	mi := &file_plugin_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchedPlugin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchedPlugin) ProtoMessage() {}

func (x *MatchedPlugin) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *MatchedPlugin) GetServices() []*network_service_go_proto.NetworkService {
	if x != nil {
		if x.xxx_hidden_Services != nil {
			return *x.xxx_hidden_Services
		}
	}
	return nil
}

func (x *MatchedPlugin) GetPlugin() *plugin_representation_go_proto.PluginDefinition {
	if x != nil {
		return x.xxx_hidden_Plugin
	}
	return nil
}

func (x *MatchedPlugin) SetServices(v []*network_service_go_proto.NetworkService) {
	x.xxx_hidden_Services = &v
}

func (x *MatchedPlugin) SetPlugin(v *plugin_representation_go_proto.PluginDefinition) {
	x.xxx_hidden_Plugin = v
}

func (x *MatchedPlugin) HasPlugin() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Plugin != nil
}

func (x *MatchedPlugin) ClearPlugin() {
	x.xxx_hidden_Plugin = nil
}

type MatchedPlugin_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// All matched network services from the reconnaissance report.
	Services []*network_service_go_proto.NetworkService
	// Plugin to run.
	Plugin *plugin_representation_go_proto.PluginDefinition
}

func (b0 MatchedPlugin_builder) Build() *MatchedPlugin {
	m0 := &MatchedPlugin{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Services = &b.Services
	x.xxx_hidden_Plugin = b.Plugin
	return m0
}

// Represents a run response with the only field being all DetectionReports
// generated by the language-specific server.
type RunResponse struct {
	state              protoimpl.MessageState                  `protogen:"opaque.v1"`
	xxx_hidden_Reports *detection_go_proto.DetectionReportList `protobuf:"bytes,1,opt,name=reports,proto3"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RunResponse) Reset() {
	*x = RunResponse{}
	mi := &file_plugin_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunResponse) ProtoMessage() {}

func (x *RunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RunResponse) GetReports() *detection_go_proto.DetectionReportList {
	if x != nil {
		return x.xxx_hidden_Reports
	}
	return nil
}

func (x *RunResponse) SetReports(v *detection_go_proto.DetectionReportList) {
	x.xxx_hidden_Reports = v
}

func (x *RunResponse) HasReports() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Reports != nil
}

func (x *RunResponse) ClearReports() {
	x.xxx_hidden_Reports = nil
}

type RunResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Reports *detection_go_proto.DetectionReportList
}

func (b0 RunResponse_builder) Build() *RunResponse {
	m0 := &RunResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Reports = b.Reports
	return m0
}

// Represents a request to list all plugins from the requested server.
type ListPluginsRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPluginsRequest) Reset() {
	*x = ListPluginsRequest{}
	mi := &file_plugin_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsRequest) ProtoMessage() {}

func (x *ListPluginsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type ListPluginsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 ListPluginsRequest_builder) Build() *ListPluginsRequest {
	m0 := &ListPluginsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

// Represents a response containing a list of all plugins
// from the requested server.
type ListPluginsResponse struct {
	state                            protoimpl.MessageState                              `protogen:"opaque.v1"`
	xxx_hidden_Plugins               *[]*plugin_representation_go_proto.PluginDefinition `protobuf:"bytes,1,rep,name=plugins,proto3"`
	xxx_hidden_WantCompactRunRequest bool                                                `protobuf:"varint,2,opt,name=want_compact_run_request,json=wantCompactRunRequest,proto3"`
	unknownFields                    protoimpl.UnknownFields
	sizeCache                        protoimpl.SizeCache
}

func (x *ListPluginsResponse) Reset() {
	*x = ListPluginsResponse{}
	mi := &file_plugin_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPluginsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPluginsResponse) ProtoMessage() {}

func (x *ListPluginsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListPluginsResponse) GetPlugins() []*plugin_representation_go_proto.PluginDefinition {
	if x != nil {
		if x.xxx_hidden_Plugins != nil {
			return *x.xxx_hidden_Plugins
		}
	}
	return nil
}

func (x *ListPluginsResponse) GetWantCompactRunRequest() bool {
	if x != nil {
		return x.xxx_hidden_WantCompactRunRequest
	}
	return false
}

func (x *ListPluginsResponse) SetPlugins(v []*plugin_representation_go_proto.PluginDefinition) {
	x.xxx_hidden_Plugins = &v
}

func (x *ListPluginsResponse) SetWantCompactRunRequest(v bool) {
	x.xxx_hidden_WantCompactRunRequest = v
}

type ListPluginsResponse_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Plugins []*plugin_representation_go_proto.PluginDefinition
	// Plugin service can indicate here that it RunRequest should be compact
	// (compact_targets should be populated instead of MatchedPlugin plugins).
	WantCompactRunRequest bool
}

func (b0 ListPluginsResponse_builder) Build() *ListPluginsResponse {
	m0 := &ListPluginsResponse{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Plugins = &b.Plugins
	x.xxx_hidden_WantCompactRunRequest = b.WantCompactRunRequest
	return m0
}

// Indexes in the following structure point to the services/plugins defined
// below. (The order is safe, guaranteed by the proto specification: "The
// order of the elements with respect to each other is preserved when parsing,
// though the ordering with respect to other fields is lost.")
type RunCompactRequest_PluginNetworkServiceTarget struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_PluginIndex  uint32                 `protobuf:"varint,1,opt,name=plugin_index,json=pluginIndex,proto3"`
	xxx_hidden_ServiceIndex uint32                 `protobuf:"varint,2,opt,name=service_index,json=serviceIndex,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *RunCompactRequest_PluginNetworkServiceTarget) Reset() {
	*x = RunCompactRequest_PluginNetworkServiceTarget{}
	mi := &file_plugin_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunCompactRequest_PluginNetworkServiceTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunCompactRequest_PluginNetworkServiceTarget) ProtoMessage() {}

func (x *RunCompactRequest_PluginNetworkServiceTarget) ProtoReflect() protoreflect.Message {
	mi := &file_plugin_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RunCompactRequest_PluginNetworkServiceTarget) GetPluginIndex() uint32 {
	if x != nil {
		return x.xxx_hidden_PluginIndex
	}
	return 0
}

func (x *RunCompactRequest_PluginNetworkServiceTarget) GetServiceIndex() uint32 {
	if x != nil {
		return x.xxx_hidden_ServiceIndex
	}
	return 0
}

func (x *RunCompactRequest_PluginNetworkServiceTarget) SetPluginIndex(v uint32) {
	x.xxx_hidden_PluginIndex = v
}

func (x *RunCompactRequest_PluginNetworkServiceTarget) SetServiceIndex(v uint32) {
	x.xxx_hidden_ServiceIndex = v
}

type RunCompactRequest_PluginNetworkServiceTarget_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The index of the plugin to run.
	PluginIndex uint32
	// The index of the network service to run against.
	ServiceIndex uint32
}

func (b0 RunCompactRequest_PluginNetworkServiceTarget_builder) Build() *RunCompactRequest_PluginNetworkServiceTarget {
	m0 := &RunCompactRequest_PluginNetworkServiceTarget{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_PluginIndex = b.PluginIndex
	x.xxx_hidden_ServiceIndex = b.ServiceIndex
	return m0
}

var File_plugin_service_proto protoreflect.FileDescriptor

const file_plugin_service_proto_rawDesc = "" +
	"\n" +
	"\x14plugin_service.proto\x12\rtsunami.proto\x1a\x0fdetection.proto\x1a\x15network_service.proto\x1a\x1bplugin_representation.proto\x1a\x14reconnaissance.proto\"w\n" +
	"\n" +
	"RunRequest\x121\n" +
	"\x06target\x18\x01 \x01(\v2\x19.tsunami.proto.TargetInfoR\x06target\x126\n" +
	"\aplugins\x18\x02 \x03(\v2\x1c.tsunami.proto.MatchedPluginR\aplugins\"\x82\x03\n" +
	"\x11RunCompactRequest\x121\n" +
	"\x06target\x18\x01 \x01(\v2\x19.tsunami.proto.TargetInfoR\x06target\x129\n" +
	"\bservices\x18\x02 \x03(\v2\x1d.tsunami.proto.NetworkServiceR\bservices\x129\n" +
	"\aplugins\x18\x03 \x03(\v2\x1f.tsunami.proto.PluginDefinitionR\aplugins\x12^\n" +
	"\fscan_targets\x18\x04 \x03(\v2;.tsunami.proto.RunCompactRequest.PluginNetworkServiceTargetR\vscanTargets\x1ad\n" +
	"\x1aPluginNetworkServiceTarget\x12!\n" +
	"\fplugin_index\x18\x01 \x01(\rR\vpluginIndex\x12#\n" +
	"\rservice_index\x18\x02 \x01(\rR\fserviceIndex\"\x83\x01\n" +
	"\rMatchedPlugin\x129\n" +
	"\bservices\x18\x01 \x03(\v2\x1d.tsunami.proto.NetworkServiceR\bservices\x127\n" +
	"\x06plugin\x18\x02 \x01(\v2\x1f.tsunami.proto.PluginDefinitionR\x06plugin\"K\n" +
	"\vRunResponse\x12<\n" +
	"\areports\x18\x01 \x01(\v2\".tsunami.proto.DetectionReportListR\areports\"\x14\n" +
	"\x12ListPluginsRequest\"\x89\x01\n" +
	"\x13ListPluginsResponse\x129\n" +
	"\aplugins\x18\x01 \x03(\v2\x1f.tsunami.proto.PluginDefinitionR\aplugins\x127\n" +
	"\x18want_compact_run_request\x18\x02 \x01(\bR\x15wantCompactRunRequest2\xf5\x01\n" +
	"\rPluginService\x12>\n" +
	"\x03Run\x12\x19.tsunami.proto.RunRequest\x1a\x1a.tsunami.proto.RunResponse\"\x00\x12L\n" +
	"\n" +
	"RunCompact\x12 .tsunami.proto.RunCompactRequest\x1a\x1a.tsunami.proto.RunResponse\"\x00\x12V\n" +
	"\vListPlugins\x12!.tsunami.proto.ListPluginsRequest\x1a\".tsunami.proto.ListPluginsResponse\"\x00B~\n" +
	"\x18com.google.tsunami.protoB\x13PluginServiceProtosP\x01ZKgithub.com/google/tsunami-security-scanner/proto/go/plugin_service_go_protob\x06proto3"

var file_plugin_service_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_plugin_service_proto_goTypes = []any{
	(*RunRequest)(nil),                                      // 0: tsunami.proto.RunRequest
	(*RunCompactRequest)(nil),                               // 1: tsunami.proto.RunCompactRequest
	(*MatchedPlugin)(nil),                                   // 2: tsunami.proto.MatchedPlugin
	(*RunResponse)(nil),                                     // 3: tsunami.proto.RunResponse
	(*ListPluginsRequest)(nil),                              // 4: tsunami.proto.ListPluginsRequest
	(*ListPluginsResponse)(nil),                             // 5: tsunami.proto.ListPluginsResponse
	(*RunCompactRequest_PluginNetworkServiceTarget)(nil),    // 6: tsunami.proto.RunCompactRequest.PluginNetworkServiceTarget
	(*reconnaissance_go_proto.TargetInfo)(nil),              // 7: tsunami.proto.TargetInfo
	(*network_service_go_proto.NetworkService)(nil),         // 8: tsunami.proto.NetworkService
	(*plugin_representation_go_proto.PluginDefinition)(nil), // 9: tsunami.proto.PluginDefinition
	(*detection_go_proto.DetectionReportList)(nil),          // 10: tsunami.proto.DetectionReportList
}
var file_plugin_service_proto_depIdxs = []int32{
	7,  // 0: tsunami.proto.RunRequest.target:type_name -> tsunami.proto.TargetInfo
	2,  // 1: tsunami.proto.RunRequest.plugins:type_name -> tsunami.proto.MatchedPlugin
	7,  // 2: tsunami.proto.RunCompactRequest.target:type_name -> tsunami.proto.TargetInfo
	8,  // 3: tsunami.proto.RunCompactRequest.services:type_name -> tsunami.proto.NetworkService
	9,  // 4: tsunami.proto.RunCompactRequest.plugins:type_name -> tsunami.proto.PluginDefinition
	6,  // 5: tsunami.proto.RunCompactRequest.scan_targets:type_name -> tsunami.proto.RunCompactRequest.PluginNetworkServiceTarget
	8,  // 6: tsunami.proto.MatchedPlugin.services:type_name -> tsunami.proto.NetworkService
	9,  // 7: tsunami.proto.MatchedPlugin.plugin:type_name -> tsunami.proto.PluginDefinition
	10, // 8: tsunami.proto.RunResponse.reports:type_name -> tsunami.proto.DetectionReportList
	9,  // 9: tsunami.proto.ListPluginsResponse.plugins:type_name -> tsunami.proto.PluginDefinition
	0,  // 10: tsunami.proto.PluginService.Run:input_type -> tsunami.proto.RunRequest
	1,  // 11: tsunami.proto.PluginService.RunCompact:input_type -> tsunami.proto.RunCompactRequest
	4,  // 12: tsunami.proto.PluginService.ListPlugins:input_type -> tsunami.proto.ListPluginsRequest
	3,  // 13: tsunami.proto.PluginService.Run:output_type -> tsunami.proto.RunResponse
	3,  // 14: tsunami.proto.PluginService.RunCompact:output_type -> tsunami.proto.RunResponse
	5,  // 15: tsunami.proto.PluginService.ListPlugins:output_type -> tsunami.proto.ListPluginsResponse
	13, // [13:16] is the sub-list for method output_type
	10, // [10:13] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_plugin_service_proto_init() }
func file_plugin_service_proto_init() {
	if File_plugin_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_plugin_service_proto_rawDesc), len(file_plugin_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plugin_service_proto_goTypes,
		DependencyIndexes: file_plugin_service_proto_depIdxs,
		MessageInfos:      file_plugin_service_proto_msgTypes,
	}.Build()
	File_plugin_service_proto = out.File
	file_plugin_service_proto_goTypes = nil
	file_plugin_service_proto_depIdxs = nil
}
