//
// Copyright 2020 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Data models for describing a scanning target.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: scan_target.proto

package scan_target_go_proto

import (
	network_go_proto "github.com/google/tsunami-security-scanner/proto/go/network_go_proto"
	network_service_go_proto "github.com/google/tsunami-security-scanner/proto/go/network_service_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The information about a scan target.
type ScanTarget struct {
	state             protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Target isScanTarget_Target    `protobuf_oneof:"target"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ScanTarget) Reset() {
	*x = ScanTarget{}
	mi := &file_scan_target_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScanTarget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScanTarget) ProtoMessage() {}

func (x *ScanTarget) ProtoReflect() protoreflect.Message {
	mi := &file_scan_target_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScanTarget) GetNetworkEndpoint() *network_go_proto.NetworkEndpoint {
	if x != nil {
		if x, ok := x.xxx_hidden_Target.(*scanTarget_NetworkEndpoint); ok {
			return x.NetworkEndpoint
		}
	}
	return nil
}

func (x *ScanTarget) GetNetworkService() *network_service_go_proto.NetworkService {
	if x != nil {
		if x, ok := x.xxx_hidden_Target.(*scanTarget_NetworkService); ok {
			return x.NetworkService
		}
	}
	return nil
}

func (x *ScanTarget) SetNetworkEndpoint(v *network_go_proto.NetworkEndpoint) {
	if v == nil {
		x.xxx_hidden_Target = nil
		return
	}
	x.xxx_hidden_Target = &scanTarget_NetworkEndpoint{v}
}

func (x *ScanTarget) SetNetworkService(v *network_service_go_proto.NetworkService) {
	if v == nil {
		x.xxx_hidden_Target = nil
		return
	}
	x.xxx_hidden_Target = &scanTarget_NetworkService{v}
}

func (x *ScanTarget) HasTarget() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Target != nil
}

func (x *ScanTarget) HasNetworkEndpoint() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Target.(*scanTarget_NetworkEndpoint)
	return ok
}

func (x *ScanTarget) HasNetworkService() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Target.(*scanTarget_NetworkService)
	return ok
}

func (x *ScanTarget) ClearTarget() {
	x.xxx_hidden_Target = nil
}

func (x *ScanTarget) ClearNetworkEndpoint() {
	if _, ok := x.xxx_hidden_Target.(*scanTarget_NetworkEndpoint); ok {
		x.xxx_hidden_Target = nil
	}
}

func (x *ScanTarget) ClearNetworkService() {
	if _, ok := x.xxx_hidden_Target.(*scanTarget_NetworkService); ok {
		x.xxx_hidden_Target = nil
	}
}

const ScanTarget_Target_not_set_case case_ScanTarget_Target = 0
const ScanTarget_NetworkEndpoint_case case_ScanTarget_Target = 1
const ScanTarget_NetworkService_case case_ScanTarget_Target = 2

func (x *ScanTarget) WhichTarget() case_ScanTarget_Target {
	if x == nil {
		return ScanTarget_Target_not_set_case
	}
	switch x.xxx_hidden_Target.(type) {
	case *scanTarget_NetworkEndpoint:
		return ScanTarget_NetworkEndpoint_case
	case *scanTarget_NetworkService:
		return ScanTarget_NetworkService_case
	default:
		return ScanTarget_Target_not_set_case
	}
}

type ScanTarget_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Target:
	// The network endpoint to be scanned.
	NetworkEndpoint *network_go_proto.NetworkEndpoint
	// The network service to be scanned.
	NetworkService *network_service_go_proto.NetworkService
	// -- end of xxx_hidden_Target
}

func (b0 ScanTarget_builder) Build() *ScanTarget {
	m0 := &ScanTarget{}
	b, x := &b0, m0
	_, _ = b, x
	if b.NetworkEndpoint != nil {
		x.xxx_hidden_Target = &scanTarget_NetworkEndpoint{b.NetworkEndpoint}
	}
	if b.NetworkService != nil {
		x.xxx_hidden_Target = &scanTarget_NetworkService{b.NetworkService}
	}
	return m0
}

type case_ScanTarget_Target protoreflect.FieldNumber

func (x case_ScanTarget_Target) String() string {
	md := file_scan_target_proto_msgTypes[0].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isScanTarget_Target interface {
	isScanTarget_Target()
}

type scanTarget_NetworkEndpoint struct {
	// The network endpoint to be scanned.
	NetworkEndpoint *network_go_proto.NetworkEndpoint `protobuf:"bytes,1,opt,name=network_endpoint,json=networkEndpoint,proto3,oneof"`
}

type scanTarget_NetworkService struct {
	// The network service to be scanned.
	NetworkService *network_service_go_proto.NetworkService `protobuf:"bytes,2,opt,name=network_service,json=networkService,proto3,oneof"`
}

func (*scanTarget_NetworkEndpoint) isScanTarget_Target() {}

func (*scanTarget_NetworkService) isScanTarget_Target() {}

var File_scan_target_proto protoreflect.FileDescriptor

const file_scan_target_proto_rawDesc = "" +
	"\n" +
	"\x11scan_target.proto\x12\rtsunami.proto\x1a\rnetwork.proto\x1a\x15network_service.proto\"\xad\x01\n" +
	"\n" +
	"ScanTarget\x12K\n" +
	"\x10network_endpoint\x18\x01 \x01(\v2\x1e.tsunami.proto.NetworkEndpointH\x00R\x0fnetworkEndpoint\x12H\n" +
	"\x0fnetwork_service\x18\x02 \x01(\v2\x1d.tsunami.proto.NetworkServiceH\x00R\x0enetworkServiceB\b\n" +
	"\x06targetBx\n" +
	"\x18com.google.tsunami.protoB\x10ScanTargetProtosP\x01ZHgithub.com/google/tsunami-security-scanner/proto/go/scan_target_go_protob\x06proto3"

var file_scan_target_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_scan_target_proto_goTypes = []any{
	(*ScanTarget)(nil),                              // 0: tsunami.proto.ScanTarget
	(*network_go_proto.NetworkEndpoint)(nil),        // 1: tsunami.proto.NetworkEndpoint
	(*network_service_go_proto.NetworkService)(nil), // 2: tsunami.proto.NetworkService
}
var file_scan_target_proto_depIdxs = []int32{
	1, // 0: tsunami.proto.ScanTarget.network_endpoint:type_name -> tsunami.proto.NetworkEndpoint
	2, // 1: tsunami.proto.ScanTarget.network_service:type_name -> tsunami.proto.NetworkService
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_scan_target_proto_init() }
func file_scan_target_proto_init() {
	if File_scan_target_proto != nil {
		return
	}
	file_scan_target_proto_msgTypes[0].OneofWrappers = []any{
		(*scanTarget_NetworkEndpoint)(nil),
		(*scanTarget_NetworkService)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_scan_target_proto_rawDesc), len(file_scan_target_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_scan_target_proto_goTypes,
		DependencyIndexes: file_scan_target_proto_depIdxs,
		MessageInfos:      file_scan_target_proto_msgTypes,
	}.Build()
	File_scan_target_proto = out.File
	file_scan_target_proto_goTypes = nil
	file_scan_target_proto_depIdxs = nil
}
