//
// Copyright 2019 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Data models for all the reconnaissance information gathered by Tsunami.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: reconnaissance.proto

package reconnaissance_go_proto

import (
	network_go_proto "github.com/google/tsunami-security-scanner/proto/go/network_go_proto"
	network_service_go_proto "github.com/google/tsunami-security-scanner/proto/go/network_service_go_proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Detailed information about the scanning target.
type TargetInfo struct {
	state                             protoimpl.MessageState               `protogen:"opaque.v1"`
	xxx_hidden_NetworkEndpoints       *[]*network_go_proto.NetworkEndpoint `protobuf:"bytes,1,rep,name=network_endpoints,json=networkEndpoints,proto3"`
	xxx_hidden_OperatingSystemClasses *[]*OperatingSystemClass             `protobuf:"bytes,2,rep,name=operating_system_classes,json=operatingSystemClasses,proto3"`
	unknownFields                     protoimpl.UnknownFields
	sizeCache                         protoimpl.SizeCache
}

func (x *TargetInfo) Reset() {
	*x = TargetInfo{}
	mi := &file_reconnaissance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetInfo) ProtoMessage() {}

func (x *TargetInfo) ProtoReflect() protoreflect.Message {
	mi := &file_reconnaissance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *TargetInfo) GetNetworkEndpoints() []*network_go_proto.NetworkEndpoint {
	if x != nil {
		if x.xxx_hidden_NetworkEndpoints != nil {
			return *x.xxx_hidden_NetworkEndpoints
		}
	}
	return nil
}

func (x *TargetInfo) GetOperatingSystemClasses() []*OperatingSystemClass {
	if x != nil {
		if x.xxx_hidden_OperatingSystemClasses != nil {
			return *x.xxx_hidden_OperatingSystemClasses
		}
	}
	return nil
}

func (x *TargetInfo) SetNetworkEndpoints(v []*network_go_proto.NetworkEndpoint) {
	x.xxx_hidden_NetworkEndpoints = &v
}

func (x *TargetInfo) SetOperatingSystemClasses(v []*OperatingSystemClass) {
	x.xxx_hidden_OperatingSystemClasses = &v
}

type TargetInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// All the known network endpoints of the scanning target.
	NetworkEndpoints       []*network_go_proto.NetworkEndpoint
	OperatingSystemClasses []*OperatingSystemClass
}

func (b0 TargetInfo_builder) Build() *TargetInfo {
	m0 := &TargetInfo{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NetworkEndpoints = &b.NetworkEndpoints
	x.xxx_hidden_OperatingSystemClasses = &b.OperatingSystemClasses
	return m0
}

// Represents a ForOperatingSystem annotation placeholder used by the
// PluginDefinition proto above.
// For possible values, consult the following database:
// https://raw.githubusercontent.com/nmap/nmap/master/nmap-os-db
type OperatingSystemClass struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Type         string                 `protobuf:"bytes,1,opt,name=type,proto3"`
	xxx_hidden_Vendor       string                 `protobuf:"bytes,2,opt,name=vendor,proto3"`
	xxx_hidden_OsFamily     string                 `protobuf:"bytes,3,opt,name=os_family,json=osFamily,proto3"`
	xxx_hidden_OsGeneration string                 `protobuf:"bytes,4,opt,name=os_generation,json=osGeneration,proto3"`
	xxx_hidden_Accuracy     uint32                 `protobuf:"varint,5,opt,name=accuracy,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *OperatingSystemClass) Reset() {
	*x = OperatingSystemClass{}
	mi := &file_reconnaissance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperatingSystemClass) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperatingSystemClass) ProtoMessage() {}

func (x *OperatingSystemClass) ProtoReflect() protoreflect.Message {
	mi := &file_reconnaissance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *OperatingSystemClass) GetType() string {
	if x != nil {
		return x.xxx_hidden_Type
	}
	return ""
}

func (x *OperatingSystemClass) GetVendor() string {
	if x != nil {
		return x.xxx_hidden_Vendor
	}
	return ""
}

func (x *OperatingSystemClass) GetOsFamily() string {
	if x != nil {
		return x.xxx_hidden_OsFamily
	}
	return ""
}

func (x *OperatingSystemClass) GetOsGeneration() string {
	if x != nil {
		return x.xxx_hidden_OsGeneration
	}
	return ""
}

func (x *OperatingSystemClass) GetAccuracy() uint32 {
	if x != nil {
		return x.xxx_hidden_Accuracy
	}
	return 0
}

func (x *OperatingSystemClass) SetType(v string) {
	x.xxx_hidden_Type = v
}

func (x *OperatingSystemClass) SetVendor(v string) {
	x.xxx_hidden_Vendor = v
}

func (x *OperatingSystemClass) SetOsFamily(v string) {
	x.xxx_hidden_OsFamily = v
}

func (x *OperatingSystemClass) SetOsGeneration(v string) {
	x.xxx_hidden_OsGeneration = v
}

func (x *OperatingSystemClass) SetAccuracy(v uint32) {
	x.xxx_hidden_Accuracy = v
}

type OperatingSystemClass_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// The type of the target operating system, e.g. "general purpose"
	Type string
	// The vendor of the target operating system, e.g. "Linux"
	Vendor string
	// The family of the target operating system, e.g. "Linux"
	OsFamily string
	// The generation of the target operating system, e.g. "2.6.X"
	OsGeneration string
	// The estimated accuracy of the target operating system, e.g. 90
	Accuracy uint32
}

func (b0 OperatingSystemClass_builder) Build() *OperatingSystemClass {
	m0 := &OperatingSystemClass{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Type = b.Type
	x.xxx_hidden_Vendor = b.Vendor
	x.xxx_hidden_OsFamily = b.OsFamily
	x.xxx_hidden_OsGeneration = b.OsGeneration
	x.xxx_hidden_Accuracy = b.Accuracy
	return m0
}

// Report from a port scanner.
type PortScanningReport struct {
	state                      protoimpl.MessageState                      `protogen:"opaque.v1"`
	xxx_hidden_TargetInfo      *TargetInfo                                 `protobuf:"bytes,1,opt,name=target_info,json=targetInfo,proto3"`
	xxx_hidden_NetworkServices *[]*network_service_go_proto.NetworkService `protobuf:"bytes,2,rep,name=network_services,json=networkServices,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *PortScanningReport) Reset() {
	*x = PortScanningReport{}
	mi := &file_reconnaissance_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PortScanningReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PortScanningReport) ProtoMessage() {}

func (x *PortScanningReport) ProtoReflect() protoreflect.Message {
	mi := &file_reconnaissance_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *PortScanningReport) GetTargetInfo() *TargetInfo {
	if x != nil {
		return x.xxx_hidden_TargetInfo
	}
	return nil
}

func (x *PortScanningReport) GetNetworkServices() []*network_service_go_proto.NetworkService {
	if x != nil {
		if x.xxx_hidden_NetworkServices != nil {
			return *x.xxx_hidden_NetworkServices
		}
	}
	return nil
}

func (x *PortScanningReport) SetTargetInfo(v *TargetInfo) {
	x.xxx_hidden_TargetInfo = v
}

func (x *PortScanningReport) SetNetworkServices(v []*network_service_go_proto.NetworkService) {
	x.xxx_hidden_NetworkServices = &v
}

func (x *PortScanningReport) HasTargetInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TargetInfo != nil
}

func (x *PortScanningReport) ClearTargetInfo() {
	x.xxx_hidden_TargetInfo = nil
}

type PortScanningReport_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Information about the scanning target.
	TargetInfo *TargetInfo
	// List of all the exposed network services.
	NetworkServices []*network_service_go_proto.NetworkService
}

func (b0 PortScanningReport_builder) Build() *PortScanningReport {
	m0 := &PortScanningReport{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TargetInfo = b.TargetInfo
	x.xxx_hidden_NetworkServices = &b.NetworkServices
	return m0
}

// Report from a service fingerprinter.
type FingerprintingReport struct {
	state                      protoimpl.MessageState                      `protogen:"opaque.v1"`
	xxx_hidden_NetworkServices *[]*network_service_go_proto.NetworkService `protobuf:"bytes,3,rep,name=network_services,json=networkServices,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *FingerprintingReport) Reset() {
	*x = FingerprintingReport{}
	mi := &file_reconnaissance_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FingerprintingReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FingerprintingReport) ProtoMessage() {}

func (x *FingerprintingReport) ProtoReflect() protoreflect.Message {
	mi := &file_reconnaissance_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *FingerprintingReport) GetNetworkServices() []*network_service_go_proto.NetworkService {
	if x != nil {
		if x.xxx_hidden_NetworkServices != nil {
			return *x.xxx_hidden_NetworkServices
		}
	}
	return nil
}

func (x *FingerprintingReport) SetNetworkServices(v []*network_service_go_proto.NetworkService) {
	x.xxx_hidden_NetworkServices = &v
}

type FingerprintingReport_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// List of all the identified network services after fingerprinting.
	NetworkServices []*network_service_go_proto.NetworkService
}

func (b0 FingerprintingReport_builder) Build() *FingerprintingReport {
	m0 := &FingerprintingReport{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_NetworkServices = &b.NetworkServices
	return m0
}

// Full reconnaissance report about a single scanning target.
type ReconnaissanceReport struct {
	state                      protoimpl.MessageState                      `protogen:"opaque.v1"`
	xxx_hidden_TargetInfo      *TargetInfo                                 `protobuf:"bytes,1,opt,name=target_info,json=targetInfo,proto3"`
	xxx_hidden_NetworkServices *[]*network_service_go_proto.NetworkService `protobuf:"bytes,2,rep,name=network_services,json=networkServices,proto3"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ReconnaissanceReport) Reset() {
	*x = ReconnaissanceReport{}
	mi := &file_reconnaissance_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnaissanceReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnaissanceReport) ProtoMessage() {}

func (x *ReconnaissanceReport) ProtoReflect() protoreflect.Message {
	mi := &file_reconnaissance_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ReconnaissanceReport) GetTargetInfo() *TargetInfo {
	if x != nil {
		return x.xxx_hidden_TargetInfo
	}
	return nil
}

func (x *ReconnaissanceReport) GetNetworkServices() []*network_service_go_proto.NetworkService {
	if x != nil {
		if x.xxx_hidden_NetworkServices != nil {
			return *x.xxx_hidden_NetworkServices
		}
	}
	return nil
}

func (x *ReconnaissanceReport) SetTargetInfo(v *TargetInfo) {
	x.xxx_hidden_TargetInfo = v
}

func (x *ReconnaissanceReport) SetNetworkServices(v []*network_service_go_proto.NetworkService) {
	x.xxx_hidden_NetworkServices = &v
}

func (x *ReconnaissanceReport) HasTargetInfo() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_TargetInfo != nil
}

func (x *ReconnaissanceReport) ClearTargetInfo() {
	x.xxx_hidden_TargetInfo = nil
}

type ReconnaissanceReport_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Information about the scanning target.
	TargetInfo *TargetInfo
	// All exposed network services of the scanning target.
	NetworkServices []*network_service_go_proto.NetworkService
}

func (b0 ReconnaissanceReport_builder) Build() *ReconnaissanceReport {
	m0 := &ReconnaissanceReport{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_TargetInfo = b.TargetInfo
	x.xxx_hidden_NetworkServices = &b.NetworkServices
	return m0
}

var File_reconnaissance_proto protoreflect.FileDescriptor

const file_reconnaissance_proto_rawDesc = "" +
	"\n" +
	"\x14reconnaissance.proto\x12\rtsunami.proto\x1a\rnetwork.proto\x1a\x15network_service.proto\"\xb8\x01\n" +
	"\n" +
	"TargetInfo\x12K\n" +
	"\x11network_endpoints\x18\x01 \x03(\v2\x1e.tsunami.proto.NetworkEndpointR\x10networkEndpoints\x12]\n" +
	"\x18operating_system_classes\x18\x02 \x03(\v2#.tsunami.proto.OperatingSystemClassR\x16operatingSystemClasses\"\xa0\x01\n" +
	"\x14OperatingSystemClass\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x16\n" +
	"\x06vendor\x18\x02 \x01(\tR\x06vendor\x12\x1b\n" +
	"\tos_family\x18\x03 \x01(\tR\bosFamily\x12#\n" +
	"\ros_generation\x18\x04 \x01(\tR\fosGeneration\x12\x1a\n" +
	"\baccuracy\x18\x05 \x01(\rR\baccuracy\"\x9a\x01\n" +
	"\x12PortScanningReport\x12:\n" +
	"\vtarget_info\x18\x01 \x01(\v2\x19.tsunami.proto.TargetInfoR\n" +
	"targetInfo\x12H\n" +
	"\x10network_services\x18\x02 \x03(\v2\x1d.tsunami.proto.NetworkServiceR\x0fnetworkServices\"`\n" +
	"\x14FingerprintingReport\x12H\n" +
	"\x10network_services\x18\x03 \x03(\v2\x1d.tsunami.proto.NetworkServiceR\x0fnetworkServices\"\x9c\x01\n" +
	"\x14ReconnaissanceReport\x12:\n" +
	"\vtarget_info\x18\x01 \x01(\v2\x19.tsunami.proto.TargetInfoR\n" +
	"targetInfo\x12H\n" +
	"\x10network_services\x18\x02 \x03(\v2\x1d.tsunami.proto.NetworkServiceR\x0fnetworkServicesB\x7f\n" +
	"\x18com.google.tsunami.protoB\x14ReconnaissanceProtosP\x01ZKgithub.com/google/tsunami-security-scanner/proto/go/reconnaissance_go_protob\x06proto3"

var file_reconnaissance_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_reconnaissance_proto_goTypes = []any{
	(*TargetInfo)(nil),                              // 0: tsunami.proto.TargetInfo
	(*OperatingSystemClass)(nil),                    // 1: tsunami.proto.OperatingSystemClass
	(*PortScanningReport)(nil),                      // 2: tsunami.proto.PortScanningReport
	(*FingerprintingReport)(nil),                    // 3: tsunami.proto.FingerprintingReport
	(*ReconnaissanceReport)(nil),                    // 4: tsunami.proto.ReconnaissanceReport
	(*network_go_proto.NetworkEndpoint)(nil),        // 5: tsunami.proto.NetworkEndpoint
	(*network_service_go_proto.NetworkService)(nil), // 6: tsunami.proto.NetworkService
}
var file_reconnaissance_proto_depIdxs = []int32{
	5, // 0: tsunami.proto.TargetInfo.network_endpoints:type_name -> tsunami.proto.NetworkEndpoint
	1, // 1: tsunami.proto.TargetInfo.operating_system_classes:type_name -> tsunami.proto.OperatingSystemClass
	0, // 2: tsunami.proto.PortScanningReport.target_info:type_name -> tsunami.proto.TargetInfo
	6, // 3: tsunami.proto.PortScanningReport.network_services:type_name -> tsunami.proto.NetworkService
	6, // 4: tsunami.proto.FingerprintingReport.network_services:type_name -> tsunami.proto.NetworkService
	0, // 5: tsunami.proto.ReconnaissanceReport.target_info:type_name -> tsunami.proto.TargetInfo
	6, // 6: tsunami.proto.ReconnaissanceReport.network_services:type_name -> tsunami.proto.NetworkService
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_reconnaissance_proto_init() }
func file_reconnaissance_proto_init() {
	if File_reconnaissance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_reconnaissance_proto_rawDesc), len(file_reconnaissance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reconnaissance_proto_goTypes,
		DependencyIndexes: file_reconnaissance_proto_depIdxs,
		MessageInfos:      file_reconnaissance_proto_msgTypes,
	}.Build()
	File_reconnaissance_proto = out.File
	file_reconnaissance_proto_goTypes = nil
	file_reconnaissance_proto_depIdxs = nil
}
